toc: true
number-depth: 3
date: now
date-format: x
filters:
  - date.lua
bibliography: ref.bib
execute:
  engine: knitr
  cache: false
format:
  html:
    highlight-style: a11y
    anchor-sections: true
    tbl-cap-location: margin
    code-block-background: false
    code-block-border-left: false
    citations-hover: true
    footnote-hover: true
    code-copy: true
    code-fold: true
    code-link: true
    code-tools: true
    link-external-icon: true
    link-external-newwindow: true
    crossref:
      lst-title: List
      lst-prefix: List
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    output-file: index.html
