<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<script src="decalendar_files/libs/clipboard/clipboard.min.js"></script>
<script src="decalendar_files/libs/quarto-html/quarto.js"></script>
<script src="decalendar_files/libs/quarto-html/popper.min.js"></script>
<script src="decalendar_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="decalendar_files/libs/quarto-html/anchor.min.js"></script>
<link href="decalendar_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="decalendar_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="decalendar_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="decalendar_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="decalendar_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Decalendar and Declock</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="decalendar_files/libs/clipboard/clipboard.min.js"></script>
<script src="decalendar_files/libs/quarto-html/quarto.js"></script>
<script src="decalendar_files/libs/quarto-html/popper.min.js"></script>
<script src="decalendar_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="decalendar_files/libs/quarto-html/anchor.min.js"></script>
<link href="decalendar_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="decalendar_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="decalendar_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="decalendar_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="decalendar_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><code>Decalendar</code> and <code>Declock</code></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="sec-summary" class="level2">
<h2 class="anchored" data-anchor-id="sec-summary">Summary</h2>
<p><code>Decalendar</code> is a calendar system that aims to first peacefully co-exist with, but then ultimately replace the <a href="https://en.wikipedia.org/wiki/Gregorian_calendar">Gregorian calendar</a>. Similarly, <code>Declock</code> is a timekeeping system designed to replace <a href="https://en.wikipedia.org/wiki/Standard_time">standard time</a>. Both <code>Decalendar</code> and <code>Declock</code> use days as their base unit and derive other units from days using prefixes inspired by the metric system. To create the necessary calendar and time units, <code>Decalendar</code> groups days together, while <code>Declock</code> divides days up.</p>
</section>
<section id="similar-systems" class="level2">
<h2 class="anchored" data-anchor-id="similar-systems">Similar systems</h2>
<section id="gregorian-calendar" class="level3">
<h3 class="anchored" data-anchor-id="gregorian-calendar">Gregorian calendar</h3>
<p>Every date in the Gregorian calendar has a <code>Decalendar</code> day of the year (<code>doty</code>) equivalent. The first day of the <code>Decalendar</code> year, <code>Day 0</code>, is March 1 in the Gregorian calendar. Starting the year on March 1 positions leap days, February 29 in the Gregorian calendar and <code>Day 365</code> in <code>Decalendar</code>, at the end of the year. Therefore, <code>Decalendar</code> leap years occur one year earlier than Gregorian calendar leap years. To check if a year is a <code>Decalendar</code> leap year, we add 1 to the year and proceed with the usual calculation (<span class="math inline">\(y \mod 4 \eq 0 \land (y \mod 100 \neq 0 \lor y \mod 400 \eq 0)\)</span>) shown in the code example below.</p>
<div class="tabset-margin-container"></div><div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Leap year identification</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<section id="javascript" class="level5">
<h5 class="anchored" data-anchor-id="javascript">JavaScript</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode javascript code-with-copy"><code class="sourceCode javascript"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">isLeap</span>(y) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> y <span class="op">%</span> <span class="dv">4</span> <span class="op">==</span> <span class="dv">0</span> <span class="op">&amp;&amp;</span> y <span class="op">%</span> <span class="dv">100</span> <span class="op">!=</span> <span class="dv">0</span> <span class="op">||</span> y <span class="op">%</span> <span class="dv">400</span> <span class="op">==</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="julia" class="level5">
<h5 class="anchored" data-anchor-id="julia">Julia</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">is_leap</span>(y)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    y <span class="op">%</span> <span class="fl">4</span> <span class="op">==</span> <span class="fl">0</span> <span class="op">&amp;&amp;</span> y <span class="op">%</span> <span class="fl">100</span> <span class="op">!=</span> <span class="fl">0</span> <span class="op">||</span> y <span class="op">%</span> <span class="fl">400</span> <span class="op">==</span> <span class="fl">0</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="python" class="level5">
<h5 class="anchored" data-anchor-id="python">Python</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> is_leap(y):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> y <span class="op">%</span> <span class="dv">4</span> <span class="op">==</span> <span class="dv">0</span> <span class="kw">and</span> y <span class="op">%</span> <span class="dv">100</span> <span class="op">!=</span> <span class="dv">0</span> <span class="kw">or</span> y <span class="op">%</span> <span class="dv">400</span> <span class="op">==</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="r" class="level5">
<h5 class="anchored" data-anchor-id="r">R</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>is_leap <span class="ot">&lt;-</span> <span class="cf">function</span>(y) {</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">%%</span> <span class="dv">4</span> <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> y <span class="sc">%%</span> <span class="dv">100</span> <span class="sc">!=</span> <span class="dv">0</span> <span class="sc">|</span> y <span class="sc">%%</span> <span class="dv">400</span> <span class="sc">==</span> <span class="dv">0</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</div>
</div>
</div>
<p><code>Decalendar</code> uses <code>doty</code> numbers as dates instead of month and day-of-the-month (<code>dotm</code>) numbers, but if required, Gregorian calendar dates can provided in the <code>m+dd</code> format, where <code>m</code> is the single-digit, <a href="https://en.wikipedia.org/wiki/Hexadecimal">hexadecimal</a>-encoded month and <code>dd</code> is the double-digit, <a href="https://en.wikipedia.org/wiki/Zero-based_numbering">zero-based</a> <code>dotm</code>. The ordinal positions of September, October, November, and December in <code>Decalendar</code> match the <a href="https://en.m.wikipedia.org/wiki/Numeral_prefix#Table_of_number_prefixes_in_English">numeral prefixes</a> in their names (Sep=7, Oct=8, Nov=9, Dec=10). In <code>Decalendar</code>, January is represented by <code>A</code> and February is represented by <code>B</code> (mnemonic: <code>jAn</code>=January, <code>feB</code>=February). The table below shows the positive and negative <code>m</code> values of each Gregorian calendar month.</p>
<div id="tbl-mvals" class="anchored">
<table class="table">
<caption>Table&nbsp;1: The <code>m</code> values of Gregorian calendar months</caption>
<thead>
<tr class="header">
<th>Month</th>
<th>Pos</th>
<th>Neg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>March</td>
<td>0</td>
<td>-C</td>
</tr>
<tr class="even">
<td>April</td>
<td>1</td>
<td>-B</td>
</tr>
<tr class="odd">
<td>May</td>
<td>2</td>
<td>-A</td>
</tr>
<tr class="even">
<td>June</td>
<td>3</td>
<td>-9</td>
</tr>
<tr class="odd">
<td>July</td>
<td>4</td>
<td>-8</td>
</tr>
<tr class="even">
<td>August</td>
<td>5</td>
<td>-7</td>
</tr>
<tr class="odd">
<td>September</td>
<td>6</td>
<td>-6</td>
</tr>
<tr class="even">
<td>October</td>
<td>7</td>
<td>-5</td>
</tr>
<tr class="odd">
<td>November</td>
<td>8</td>
<td>-4</td>
</tr>
<tr class="even">
<td>December</td>
<td>9</td>
<td>-3</td>
</tr>
<tr class="odd">
<td>January</td>
<td>A</td>
<td>-2</td>
</tr>
<tr class="even">
<td>February</td>
<td>B</td>
<td>-1</td>
</tr>
</tbody>
</table>
</div>
<section id="iso-8601-dates" class="level4">
<h4 class="anchored" data-anchor-id="iso-8601-dates">ISO 8601 dates</h4>
<p>The <code>m+dd</code> format shown above is similar to the <a href="https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates">calendar date</a> format (year-mm-dd) of the <a href="https://en.wikipedia.org/wiki/ISO_8601#Ordinal_dates">ISO 8601</a> international standard for <a href="https://en.wikipedia.org/wiki/ISO_8601#Dates">dates</a> and <a href="https://en.wikipedia.org/wiki/ISO_8601#Times">times</a>. <code>Decalendar</code> dates (<code>year±day</code>) are most similar to ISO 8601 <a href="https://en.wikipedia.org/wiki/ISO_8601#Ordinal_dates">ordinal dates</a> (year-day). In fact, the <code>Decalendar</code> <code>doty</code> number can be obtained from the ISO 8601 ordinal day number using the calculation (<span class="math inline">\((ordinal + 365) \mod 365\)</span>) shown in the code example below. This calculation essentially shifts the ordinal date number to be 60 days earlier.</p>
<div class="tabset-margin-container"></div><div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">ISO ordinal day number to <code>doty</code> conversion</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<section id="javascript-1" class="level5">
<h5 class="anchored" data-anchor-id="javascript-1">JavaScript</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode javascript code-with-copy"><code class="sourceCode javascript"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">ordi2doty</span>(o) {</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (o <span class="op">+</span> <span class="dv">305</span>) <span class="op">%</span> <span class="dv">365</span><span class="op">;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="julia-1" class="level5">
<h5 class="anchored" data-anchor-id="julia-1">Julia</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">ordi2doty</span>(o)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    (o <span class="op">+</span> <span class="fl">305</span>) <span class="op">%</span> <span class="fl">365</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="python-1" class="level5">
<h5 class="anchored" data-anchor-id="python-1">Python</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ordi2doty(o):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (o <span class="op">+</span> <span class="dv">305</span>) <span class="op">%</span> <span class="dv">365</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="r-1" class="level5">
<h5 class="anchored" data-anchor-id="r-1">R</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ordi2doty <span class="ot">&lt;-</span> <span class="cf">function</span>(o) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  (o <span class="sc">+</span> <span class="dv">305</span>) <span class="sc">%%</span> <span class="dv">365</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</div>
</div>
</div>
<p>Both <code>Decalendar</code> and ISO 8601 show <a href="https://en.wikipedia.org/wiki/ISO_8601#Years">years</a> as 4-digit numbers, but unlike ISO 8601, years are not mandatory in <code>Decalendar</code> dates. The years in <code>Decalendar</code>, ISO 8601 calendar, and ISO 8601 ordinal dates will match except for in January and February when the <code>Decalendar</code> year will be 1 year less than the ISO 8601 year. Year 0 in both <code>Decalendar</code> and ISO 8601 is 1 BCE (Before Common Era) in the Gregorian calendar. The first day of Year 0 in <code>Decalendar</code>, <code>0000+000</code>, is March 1, 1 BCE in the Gregorian calendar, <code>0000-03-01</code> in the ISO 8601 calendar date format, and <code>0000-061</code> in the ISO 8601 ordinal date format.</p>
</section>
<section id="iso-8601-times" class="level4">
<h4 class="anchored" data-anchor-id="iso-8601-times">ISO 8601 times</h4>
<p>Just like <code>Decalendar</code> seeks to make months and weeks obsolete, <code>Declock</code> aims to deprecate hours, minutes, and seconds in favor of <a href="https://en.wikipedia.org/wiki/Decimal_time#Fractional_days">fractional days</a>. <code>Declock</code> and ISO 8601 each have 1 time format. Both of these formats can be appended to dates to form timestamps. <code>Declock</code> timestamps are more concise and easier to read than ISO 8601 timestamps. An ISO 8601 calendar date timestamp that includes seconds is 23 characters long (<code>year-mm-ddThh:mm:ss</code>), while a <code>Decalendar</code> timestamp with slightly greater precision is only 14 characters long (<code>year±day.ddddd</code>). Without delimiters, ISO 8601 timestamps become even more difficult to read (<code>yearmmddThhmmss</code>) and still cannot match the brevity of <code>Declock</code> timestamps.</p>
</section>
<section id="iso-8601-recurring-intervals" class="level4">
<h4 class="anchored" data-anchor-id="iso-8601-recurring-intervals">ISO 8601 recurring intervals</h4>
<p>The numbers in the <code>Decalendar</code> dates are essentially <a href="https://en.wikipedia.org/wiki/Zero-based_numbering">zero-based indexes</a> that can be positive or negative, like in computer <a href="https://en.wikipedia.org/wiki/Zero-based_numbering#Computer_programming">programming</a>. Another inspiration from computer programming, is the ability to use <a href="https://en.wikipedia.org/wiki/Array_slicing">array slicing</a> to create time intervals. For example, <a href="https://pandas.pydata.org/pandas-docs/version/1.1/user_guide/timeseries.html#indexing">indexing and slicing of dates and times</a> is fully implemented in the <a href="https://pandas.pydata.org/">Pandas Python library</a>.</p>
<p>Building on the concept of array slicing (<code>start:stop:step</code>), <code>Decalendar</code> introduces a new technique called “array spreading” (<code>start&gt;span&gt;split&gt;space</code>) and even allows for nesting and mixing of <code>slices</code> and <code>spreads</code>. The various expressions that represent dates, times, timestamps, and time intervals are collectively called <code>Decalendar strings</code>. ISO 8601 has three methods of unequivocally creating <a href="https://en.wikipedia.org/wiki/ISO_8601#Time_intervals">time intervals</a>, <code>start/stop</code>, <code>start/span</code>, and <code>span/stop</code>. The <code>Decalendar string</code> equivalents of these three interval creation methods are <code>start:stop</code>, <code>start&gt;span</code>, and <code>stop&lt;span</code>.</p>
<p>Unlike <code>Decalendar strings</code>, ISO 8601 expressions cannot create non-consecutive or overlapping recurring intervals. Consecutive recurring intervals in ISO 8601 can look like <code>Rn/start/stop</code>, <code>Rn/start/span</code>, or <code>Rn/span/stop</code>, where <code>n</code> is the number of repetitions. In <code>Decalendar</code>, consecutive intervals can be created in several ways, but the easiest is with a spread (e.g.&nbsp;<code>start&gt;span&gt;split&gt;0</code>). To create non-consecutive recurring intervals, we can set a non-zero <code>space</code> value (e.g.&nbsp;<code>start&gt;span&gt;split&gt;space</code>) to create <code>space</code>-sized breaks in between the <code>splits</code> of the <code>spread</code>. If we want the intervals to overlap, we can flip the last sign in the <code>spread</code> and the <code>space</code> becomes the size of the overlap.</p>
</section>
</section>
<section id="french-republican-calendar" class="level3">
<h3 class="anchored" data-anchor-id="french-republican-calendar">French Republican Calendar</h3>
<section id="french-republican-calendar-décades" class="level4">
<h4 class="anchored" data-anchor-id="french-republican-calendar-décades">French Republican Calendar <em>Décades</em></h4>
<p>The <a href="https://en.wikipedia.org/wiki/French_Republican_calendar">French Republican calendar</a> and <code>Decalendar</code> both organize days in groups of 10. A group of 10 days in the French Republican calendar is called a <em>décade</em>, while a group of 10 days in <code>Decalendar</code> is called a <code>dek</code>. The names of the days in a <code>Decalendar</code> <code>dek</code> are derived from their <a href="https://en.wikipedia.org/wiki/Zero-based_numbering">zero-based</a> cardinal numbers (zero, one, two…), whereas the days of the <em>décade</em> are named after their ordinal numbers (first, second, third…). The table provides the cardinal numbers, one-letter codes, names, and types of the days of the <code>dek</code> as well as the names of their French Republican calendar equivalents.</p>
<div id="tbl-dotd" class="anchored">
<table class="table">
<caption>Table&nbsp;2: The days of the <code>dek</code> and their French Republican calendar equivalents</caption>
<thead>
<tr class="header">
<th>#</th>
<th>Code</th>
<th>Name</th>
<th>Type</th>
<th>French</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>N</td>
<td>Nulday</td>
<td>work</td>
<td>primidi</td>
</tr>
<tr class="even">
<td>1</td>
<td>U</td>
<td>Unoday</td>
<td>work</td>
<td>duodi</td>
</tr>
<tr class="odd">
<td>2</td>
<td>D</td>
<td>Duoday</td>
<td>work</td>
<td>tridi</td>
</tr>
<tr class="even">
<td>3</td>
<td>T</td>
<td>Triday</td>
<td>rest</td>
<td>quartidi</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Q</td>
<td>Quaday</td>
<td>rest</td>
<td>quintidi</td>
</tr>
<tr class="even">
<td>5</td>
<td>P</td>
<td>Penday</td>
<td>work</td>
<td>sextidi</td>
</tr>
<tr class="odd">
<td>6</td>
<td>H</td>
<td>Hexday</td>
<td>work</td>
<td>septidi</td>
</tr>
<tr class="even">
<td>7</td>
<td>S</td>
<td>Sepday</td>
<td>work</td>
<td>octidi</td>
</tr>
<tr class="odd">
<td>8</td>
<td>O</td>
<td>Octday</td>
<td>rest</td>
<td>nonidi</td>
</tr>
<tr class="even">
<td>9</td>
<td>E</td>
<td>Ennday</td>
<td>rest</td>
<td>décadi</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="french-republican-calendar-decimal-time" class="level4">
<h4 class="anchored" data-anchor-id="french-republican-calendar-decimal-time">French Republican Calendar decimal time</h4>
<p>The French Republican calendar and <code>Declock</code> both the break the day down into decimal portions. In <code>Declock</code>, a <code>dime</code> is a tenth (⅒) of a day, a <code>cent</code> is a hundredth (10⁻²) of a day, a <code>mil</code> is a thousandth (10⁻³) of a day, and a <code>beat</code> is a hundred thousandth (10⁻⁵) of a day, whereas the French Republican calendar calls these units decimal hours, decimal minutes, <em>décimes</em>, and decimal seconds, respectively. The table below shows the start times of each <code>dime</code> (⅒) in a day and their equivalents in 24-hour and 12-hour standard time. When converting between standard time and <code>Declock</code>, it is important to note that, unlike standard time, <code>Declock</code> does not include <a href="https://en.wikipedia.org/wiki/Leap_second#Insertion_of_leap_seconds">leap seconds</a>.</p>
<div id="tbl-dime" class="anchored">
<table class="table">
<caption>Table&nbsp;3: The start times of each <code>dime</code> in a day and their standard time equivalents</caption>
<thead>
<tr class="header">
<th>⅒</th>
<th>24-hour</th>
<th>12-hour</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>00:00</td>
<td>12:00AM</td>
</tr>
<tr class="even">
<td>1</td>
<td>02:24</td>
<td>2:24AM</td>
</tr>
<tr class="odd">
<td>2</td>
<td>04:48</td>
<td>4:48AM</td>
</tr>
<tr class="even">
<td>3</td>
<td>07:12</td>
<td>7:12AM</td>
</tr>
<tr class="odd">
<td>4</td>
<td>09:36</td>
<td>9:36AM</td>
</tr>
<tr class="even">
<td>5</td>
<td>12:00</td>
<td>12:00PM</td>
</tr>
<tr class="odd">
<td>6</td>
<td>14:24</td>
<td>2:24PM</td>
</tr>
<tr class="even">
<td>7</td>
<td>16:48</td>
<td>4:48PM</td>
</tr>
<tr class="odd">
<td>8</td>
<td>19:12</td>
<td>7:12PM</td>
</tr>
<tr class="even">
<td>9</td>
<td>21:36</td>
<td>9:36PM</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="swatch-internet-time" class="level3">
<h3 class="anchored" data-anchor-id="swatch-internet-time">Swatch Internet Time</h3>
<p><a href="https://en.wikipedia.org/wiki/Swatch_Internet_Time">Swatch Internet Time</a> uses the term “.beats” to describe a thousandth of day (10⁻³). In <code>Declock</code>, a <code>beat</code> is a hundred thousandth of a day (10⁻⁵), because this is the approximate duration of a heartbeat or a beat of music. Another difference is that Swatch Internet Time has only 1 time zone, <a href="https://en.wikipedia.org/wiki/List_of_UTC_offsets#UTC+01:00,_A">UTC+1</a>, limiting its utility outside of Central Europe or West Africa. <code>Declock</code> has 11 main single-digit time zones, but can support as many time zones as needed by adding additional digits (110 double-digit time zones, 1100 triple-digit time zones, and so on).</p>
</section>
<section id="julian-dates" class="level3">
<h3 class="anchored" data-anchor-id="julian-dates">Julian dates</h3>
<p>Julian dates are the number of <a href="https://en.wikipedia.org/wiki/Decimal_time#Fractional_days">fractional days</a> since <code>-4713+327.5</code>, which is noon on November 24, 4714 BC in the Gregorian calendar and January 1, 4713 BC in the Julian calendar. Julian days start at noon, whereas <code>Decalendar</code> days, and some <a href="https://en.wikipedia.org/wiki/Julian_day#Variants">Julian day variants</a>, start at midnight. Like Swatch Internet Time, Julian dates only use a single time zone (<a href="https://en.wikipedia.org/wiki/List_of_UTC_offsets#UTC%C2%B100:00,_Z">UTC+0</a>). To obtain a <code>Declock</code> time from a Julian date, we obtain we subtract the Julian Day Number (<span class="math inline">\(\lfloor JD \rfloor\)</span>) from the Julian Day (<span class="math inline">\(JD\)</span>), add 0.5, and then obtaining the remainder after dividing by 1 (<span class="math inline">\((JD - \lfloor JD \rfloor + .5) \mod 1\)</span>).</p>
</section>
<section id="unix-time" class="level3">
<h3 class="anchored" data-anchor-id="unix-time">UNIX time</h3>
<p>While it is possible to convert Julian dates into <code>Decalendar</code> dates and <code>Declock</code> times, the official definition of <code>Decalendar</code> dates and <code>Declock</code> times is based on UNIX time. UNIX time is the number of seconds since the UNIX Epoch, which is <code>1969+306.0</code> in <code>Decalendar</code> or midnight on January 1, 1970 in the Gregorian calendar. A day is exactly 86,400 seconds (100,000 <code>beats</code>) long in UNIX time, Julian dates, <code>Decalendar</code> dates, and <code>Declock</code> times.</p>
<p>To calculate <code>Decalendar</code> dates and <code>Declock</code> times directly from UNIX time, the seconds (or milliseconds) in UNIX time are first converted to <code>days</code>. Then, the <code>days</code> are used to obtain the <code>year</code> using a calculation described by <a href="http://howardhinnant.github.io/date_algorithms.html#civil_from_days">Howard Hinnant in his 2021 article entitled “chrono-Compatible Low-Level Date Algorithms”</a>. Finally, the <code>year</code> is used to sum up all of the days in previous years and this sum is subtracted from the days to obtain the current <code>Decalendar</code> timestamp.</p>
<p>The code example below shows a function that converts UNIX time into a <code>Decalendar</code> timestamp. The last line in the code example obtains the current <code>Decalendar</code> timestamp by passing the current UNIX timestamp to the function. If we pass 0 to the function (<code>unix2doty(0)</code>) the result should be <code>1969+306.00000</code>. To see this function in action, visit this <a href="https://codepen.io/maptv/pen/oNJZeea">CodePen</a> which displays the current timestamps in the <code>Decalendar</code> (<code>year+day.ddddd</code>) and ISO 8601 (<code>year-mm-ddThh:mm:ss</code>) timestamp formats.</p>
<div class="tabset-margin-container"></div><div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">UNIX time conversion to Decalendar date and Declock time</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<section id="javascript-2" class="level5">
<h5 class="anchored" data-anchor-id="javascript-2">JavaScript</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode javascript code-with-copy"><code class="sourceCode javascript"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">unix2doty</span>(s <span class="op">=</span> <span class="dv">0</span><span class="op">,</span> ms <span class="op">=</span> <span class="dv">0</span>) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">const</span> days <span class="op">=</span> s <span class="op">/</span> <span class="dv">86400</span> <span class="op">+</span> ms <span class="op">/</span> <span class="dv">86400000</span> <span class="op">+</span> <span class="dv">719468</span><span class="op">,</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        era <span class="op">=</span> <span class="bu">Math</span><span class="op">.</span><span class="fu">floor</span>((days <span class="op">&gt;=</span> <span class="dv">0</span> <span class="op">?</span> days <span class="op">:</span> days <span class="op">-</span> <span class="dv">146096</span>) <span class="op">/</span> <span class="dv">146097</span>)<span class="op">,</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        doe <span class="op">=</span> days <span class="op">-</span> era <span class="op">*</span> <span class="dv">146097</span><span class="op">,</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        yoe <span class="op">=</span> <span class="bu">Math</span><span class="op">.</span><span class="fu">floor</span>((doe <span class="op">-</span> doe <span class="op">/</span> <span class="dv">1460</span> <span class="op">+</span> doe <span class="op">/</span> <span class="dv">36524</span> <span class="op">-</span> doe <span class="op">/</span> <span class="dv">146096</span>) <span class="op">/</span> <span class="dv">365</span>)<span class="op">,</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        year <span class="op">=</span> yoe <span class="op">+</span> era <span class="op">*</span> <span class="dv">400</span><span class="op">,</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        ts <span class="op">=</span> days <span class="op">-</span> (year <span class="op">*</span> <span class="dv">365</span> <span class="op">+</span> [<span class="op">...</span><span class="bu">Array</span>(year)<span class="op">.</span><span class="fu">keys</span>()]<span class="op">.</span><span class="fu">map</span>(</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>            i <span class="kw">=&gt;</span> i <span class="op">%</span> <span class="dv">4</span> <span class="op">==</span> <span class="dv">0</span> <span class="op">&amp;&amp;</span> i <span class="op">%</span> <span class="dv">100</span> <span class="op">!=</span> <span class="dv">0</span> <span class="op">||</span> i <span class="op">%</span> <span class="dv">400</span> <span class="op">==</span> <span class="dv">0</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        )<span class="op">.</span><span class="fu">reduce</span>((a<span class="op">,</span> b) <span class="kw">=&gt;</span> a <span class="op">+</span> b<span class="op">,</span> <span class="dv">0</span>)) <span class="op">+</span> <span class="dv">1</span><span class="op">,</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        doy <span class="op">=</span> <span class="bu">Math</span><span class="op">.</span><span class="fu">floor</span>(ts)<span class="op">,</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        cmd <span class="op">=</span> <span class="bu">Math</span><span class="op">.</span><span class="fu">floor</span>((ts <span class="op">-</span> doy) <span class="op">*</span> <span class="fl">1e5</span>)<span class="op">;</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="vs">`</span><span class="sc">${</span>year<span class="op">.</span><span class="fu">toString</span>()<span class="op">.</span><span class="fu">padStart</span>(<span class="dv">4</span><span class="op">,</span> <span class="st">"0"</span>)<span class="sc">}</span><span class="vs">`</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="vs">`+</span><span class="sc">${</span>doy<span class="op">.</span><span class="fu">toString</span>()<span class="op">.</span><span class="fu">padStart</span>(<span class="dv">3</span><span class="op">,</span> <span class="st">"0"</span>)<span class="sc">}</span><span class="vs">`</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> <span class="vs">`.</span><span class="sc">${</span>cmd<span class="op">.</span><span class="fu">toString</span>()<span class="op">.</span><span class="fu">padStart</span>(<span class="dv">5</span><span class="op">,</span> <span class="st">"0"</span>)<span class="sc">}</span><span class="vs">`</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="bu">console</span><span class="op">.</span><span class="fu">log</span>(<span class="fu">unix2doty</span>(<span class="dv">0</span><span class="op">,</span> <span class="bu">Date</span><span class="op">.</span><span class="fu">now</span>()))<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="julia-2" class="level5">
<h5 class="anchored" data-anchor-id="julia-2">Julia</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">function</span> <span class="fu">unix2doty</span>(s<span class="op">=</span><span class="fl">0</span>, ms<span class="op">=</span><span class="fl">0</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    days <span class="op">=</span> s <span class="op">/</span> <span class="fl">86400</span> <span class="op">+</span> ms <span class="op">/</span> <span class="fl">86400000</span> <span class="op">+</span> <span class="fl">719468</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    era <span class="op">=</span> <span class="fu">floor</span>((days <span class="op">&gt;=</span> <span class="fl">0</span> ? days <span class="op">:</span> days <span class="op">-</span> <span class="fl">146096</span>) <span class="op">/</span> <span class="fl">146097</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    doe <span class="op">=</span> days <span class="op">-</span> era <span class="op">*</span> <span class="fl">146097</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    yoe <span class="op">=</span> <span class="fu">floor</span>((doe <span class="op">-</span> doe <span class="op">/</span> <span class="fl">1460</span> <span class="op">+</span> doe <span class="op">/</span> <span class="fl">36524</span> <span class="op">-</span> doe <span class="op">/</span> <span class="fl">146096</span>) <span class="op">/</span> <span class="fl">365</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    year <span class="op">=</span> <span class="fu">Int</span>(yoe <span class="op">+</span> era <span class="op">*</span> <span class="fl">400</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    ts <span class="op">=</span> days <span class="op">-</span> (year <span class="op">*</span> <span class="fl">365</span> <span class="op">+</span> <span class="fu">sum</span>([</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        i <span class="op">%</span> <span class="fl">4</span> <span class="op">==</span> <span class="fl">0</span> <span class="op">&amp;&amp;</span> i <span class="op">%</span> <span class="fl">100</span> <span class="op">!=</span> <span class="fl">0</span> <span class="op">||</span> i <span class="op">%</span> <span class="fl">400</span> <span class="op">==</span> <span class="fl">0</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>        for i <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span>year<span class="op">-</span><span class="fl">1</span>]))</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    doy <span class="op">=</span> <span class="fu">Int</span>(<span class="fu">floor</span>(ts))</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    cmd <span class="op">=</span> <span class="fu">Int</span>(<span class="fu">round</span>((ts <span class="op">-</span> doy) <span class="op">*</span> <span class="fl">1e5</span>))</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"</span><span class="sc">$</span>(<span class="fu">lpad</span>(year,<span class="fl">4</span>,<span class="ch">'0'</span>))<span class="st">+</span><span class="sc">$</span>(<span class="fu">lpad</span>(doy,<span class="fl">3</span>,<span class="ch">'0'</span>))<span class="st">.</span><span class="sc">$</span>(<span class="fu">lpad</span>(cmd,<span class="fl">5</span>,<span class="ch">'0'</span>))<span class="st">"</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="kw">end</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="fu">unix2doty</span>(<span class="fu">time</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="python-2" class="level5">
<h5 class="anchored" data-anchor-id="python-2">Python</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> time <span class="im">import</span> time</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> unix2doty(s<span class="op">=</span><span class="dv">0</span>, ms<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    days <span class="op">=</span> s <span class="op">/</span> <span class="dv">86400</span> <span class="op">+</span> ms <span class="op">/</span> <span class="dv">86400000</span> <span class="op">+</span> <span class="dv">719468</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    era <span class="op">=</span> (days <span class="cf">if</span> days <span class="op">&gt;=</span> <span class="dv">0</span> <span class="cf">else</span> days <span class="op">-</span> <span class="dv">146096</span>) <span class="op">//</span> <span class="dv">146097</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    doe <span class="op">=</span> days <span class="op">-</span> era <span class="op">*</span> <span class="dv">146097</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    yoe <span class="op">=</span> (doe <span class="op">-</span> doe <span class="op">/</span> <span class="dv">1460</span> <span class="op">+</span> doe <span class="op">/</span> <span class="dv">36524</span> <span class="op">-</span> doe <span class="op">/</span> <span class="dv">146096</span>) <span class="op">//</span> <span class="dv">365</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    year <span class="op">=</span> <span class="bu">int</span>(yoe <span class="op">+</span> era <span class="op">*</span> <span class="dv">400</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    ts <span class="op">=</span> days <span class="op">-</span> (year <span class="op">*</span> <span class="dv">365</span> <span class="op">+</span> <span class="bu">sum</span>(</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>        i <span class="op">%</span> <span class="dv">4</span> <span class="op">==</span> <span class="dv">0</span> <span class="kw">and</span> i <span class="op">%</span> <span class="dv">100</span> <span class="op">!=</span> <span class="dv">0</span> <span class="kw">or</span> i <span class="op">%</span> <span class="dv">400</span> <span class="op">==</span> <span class="dv">0</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(year))) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    doy <span class="op">=</span> <span class="bu">int</span>(ts.<span class="fu">__floor__</span>())</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="ss">f"</span><span class="sc">{</span>year<span class="sc">:0&lt;4}</span><span class="ss">+</span><span class="sc">{</span>doy<span class="sc">:0&lt;3}</span><span class="ss">.</span><span class="sc">{</span><span class="bu">round</span>((ts <span class="op">-</span> doy) <span class="op">*</span> <span class="fl">1e5</span>)<span class="sc">:0&lt;5}</span><span class="ss">"</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>unix2doty(time())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="r-2" class="level5">
<h5 class="anchored" data-anchor-id="r-2">R</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>unix2doty <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">s =</span> <span class="dv">0</span>, <span class="at">ms =</span> <span class="dv">0</span>) {</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  days <span class="ot">=</span> s <span class="sc">/</span> <span class="dv">86400</span> <span class="sc">+</span> ms <span class="sc">/</span> <span class="dv">86400000</span> <span class="sc">+</span> <span class="dv">719468</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  era <span class="ot">=</span> <span class="fu">floor</span>(<span class="fu">ifelse</span>(days <span class="sc">&gt;=</span> <span class="dv">0</span>, days, days <span class="sc">-</span> <span class="dv">146096</span>) <span class="sc">/</span> <span class="dv">146097</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  doe <span class="ot">=</span> days <span class="sc">-</span> era <span class="sc">*</span> <span class="dv">146097</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  yoe <span class="ot">=</span> <span class="fu">floor</span>((doe <span class="sc">-</span> doe <span class="sc">/</span> <span class="dv">1460</span> <span class="sc">+</span> doe <span class="sc">/</span> <span class="dv">36524</span> <span class="sc">-</span> doe <span class="sc">/</span> <span class="dv">146096</span>) <span class="sc">/</span> <span class="dv">365</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  year <span class="ot">=</span> yoe <span class="sc">+</span> era <span class="sc">*</span> <span class="dv">400</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  years <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span>year</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  ts <span class="ot">=</span> days <span class="sc">-</span> (year <span class="sc">*</span> <span class="dv">365</span> <span class="sc">+</span> <span class="fu">sum</span>(</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    years <span class="sc">%%</span> <span class="dv">4</span> <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> years <span class="sc">%%</span> <span class="dv">100</span> <span class="sc">!=</span> <span class="dv">0</span> <span class="sc">|</span> years <span class="sc">%%</span> <span class="dv">400</span> <span class="sc">==</span> <span class="dv">0</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  doy <span class="ot">=</span> <span class="fu">floor</span>(ts)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  cmd <span class="ot">=</span> <span class="fu">round</span>((ts <span class="sc">-</span> doy) <span class="sc">*</span> <span class="fl">1e5</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sprintf</span>(<span class="st">"%04d"</span>, year),</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"+"</span>, <span class="fu">sprintf</span>(<span class="st">"%03d"</span>, doy),</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"."</span>, <span class="fu">sprintf</span>(<span class="st">"%05d"</span>, cmd)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="fu">unix2doty</span>(<span class="fu">as.numeric</span>(<span class="fu">Sys.time</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</div>
</div>
</div>
</section>
</section>
<section id="sec-basics" class="level2">
<h2 class="anchored" data-anchor-id="sec-basics">Basic concepts</h2>
<section id="sec-frac" class="level3">
<h3 class="anchored" data-anchor-id="sec-frac">Fractions analogy</h3>
<p>In the simplest terms, <code>Decalendar</code> counts fractions of a year, while <code>Declock</code> counts fractions of a day. The denominator for <code>Decalendar</code> is the number of days in the year, and the <code>Declock</code> denominator is <span class="math inline">\(10^x\)</span>, where <span class="math inline">\(x\)</span> is the number of digits in the numerator. In both systems, only the numerator, not the denominator, is provided. In the context of<code>Decalendar</code>, the numerator is the days that have passed in the year, while in the context of<code>Declock</code>, the numerator is the parts of the day that have passed.</p>
<p>To avoid any confusion between the two, we can say “<code>Day 5</code>” to mean the date when 5 days have passed this year or <code>Day 0</code> to mean the first day of the year (<code>doty</code>). This is like the use of the term “day zero” in other contexts, such as epidemiology. The analogous term for times is <code>Dot</code>. The word <code>Dot</code> conveys that at its core <code>Declock</code> is a system built on fractional days expressed as decimal numbers. The 5 in <code>Dot 5</code> can be thought of as a number after a decimal (0.5) or a numerator (⁵/₁₀), either way it means noon, the time when half the day has passed.</p>
</section>
<section id="sec-imp" class="level3">
<h3 class="anchored" data-anchor-id="sec-imp">Implied tolerance and duration</h3>
<p>The analogy to decimals or fractions is important, because it explains why adding a zero at the end of a time does not change the time, only the implied tolerance of time points or the implied duration of time intervals. If <code>Dot 5</code> is a time point, it has an implied tolerance of 5% of the day (<code>.5±.05</code>), because any time after <code>Dot 45</code> and before <code>Dot 55</code> (<code>[.45, .55)</code>) would round to <code>Dot 5</code>. On the other hand, if <code>Dot 5</code> is the start time for a time interval, that interval is implied to start at <code>Dot 5</code> and end before <code>Dot 6</code> (<code>[.5, .6)</code>) and thus have a duration of 10% of the day (<code>Dot 6</code>-<code>Dot 5</code>). Every additional digit we add decreases the implied tolerance and the implied duration 10-fold.</p>
<p>If we really want to insist on punctuality, we could include up to 5 digits in a time. Specifying times with more than 5 digits is possible, and may be useful for scientific or technical purposes, but it is analogous to providing <a href="https://xkcd.com/2170/">extremely long GPS coordinates</a>; at some point the level of precision stops having relevance to daily life. If we want to strive for the highest level of precision possible, we can add the word “sharp” or the <code>#</code> symbol to the time. Saying “<code>5 Sharp</code>” or writing <code>5#</code> means as close as possible to noon. Times that include <code>#</code> cannot have an implied duration. We can only add <code>#</code> to a time, so there is no need say “<code>Dot 5 Sharp</code>” or write <code>.5#</code>.</p>
</section>
<section id="sec-context" class="level3">
<h3 class="anchored" data-anchor-id="sec-context">Context clues</h3>
<p>Not saying “<code>Day</code>” or “<code>Dot</code>” in general is acceptable, because it is convenient and often the numbers make perfect sense in context. If someone says “let’s have lunch at 5”, it is clear that they are referring to noon (<code>Dot 5</code>) and not the sixth <code>doty</code> (<code>Day 5</code>). Also, the number itself may provide a clue. Numbers greater than 365 could still be a <code>doty</code> date, but such dates would be in an upcoming year, not the current year. The meaning of such dates depends on whether the current year is a common year (n=365) or a leap year (n=366). Saying “500” could mean <code>Day 134</code> (if n=366) or <code>Day 135</code> (if n=365) of the subsequent year, but it would most likely mean noon (<code>Dot 500</code>).</p>
</section>
<section id="stamps" class="level3">
<h3 class="anchored" data-anchor-id="stamps"><code>Stamps</code></h3>
<p>If a date and a time are combined they form a time <code>stamp</code>. The date always goes before the time in any <code>stamp</code>. When said together, the numbers “0” and “500” mean the first <code>doty</code> (<code>Day 0</code>) at noon (<code>Dot 500</code>). In written form, this would be <code>000.500</code>. This format is called <code>.y</code>, which is read the same way as <code>doty</code>, but emphasizes that the <code>.</code> is used in a floating point decimal <code>doty</code>. In other words, <code>doty</code> can be used instead of “day of the year” in a sentence, whereas <code>.y</code> indicates a <code>stamp</code>, such as <code>000.500</code>. Ideally, a stamp will include all of the information needed to identify a singular point in time, and thus should include a year and time zone.</p>
</section>
<section id="sec-specific" class="level3">
<h3 class="anchored" data-anchor-id="sec-specific">Specific dates and times</h3>
<p>The dates and times above assume that the year and time zone are known. A date without a year is like a time without a time zone, both depend on the context. Most likely, we are talking about the current year and the local time zone, but it may be unclear. Including a year allows us to pinpoint a specific day, instead of a day that could happen any year. Similarly, a time with a time zone occurs once a day, rather than once in every time zone per day. The first <code>doty</code> 2000, would be written <code>2000+000</code> and said “<code>Year 2000 Day 0</code>” or simply “<code>2000 0</code>”, while noon in <code>Zone 0</code> would be written <code>.500+0</code> or <code>500+0</code> and said “<code>Dot 500 Zone 0</code>”, “<code>500 Zone 0</code>”, or “<code>500 0</code>”.</p>
</section>
<section id="sec-neg" class="level3">
<h3 class="anchored" data-anchor-id="sec-neg">Negative numbers</h3>
<p>The plus signs in the date and time above indicate that the <code>doty</code> date and the time zone can also be negative. In fact, all of the units above can be negative. A negative year is before 1 BCE (Before Common Era) and a negative time zone is West of <code>Zone 0</code>. Negative dates and times show the number of parts that are left in the whole (day or year). To extend the fractions analogy used above to negative numbers, the negative number added to the whole gives us the numerator of the positive fraction. Essentially, these numbers arrive at the same answer from opposite directions.</p>
<p>Negative <code>doty</code> numbers can be especially useful at the end of the year, because <code>Day -1</code> is always the last <code>doty</code>, regardless of whether the year has 365 or 366 days. In certain contexts, the choice of using a negative number over a positive number may mean that we want to emphasize how much time is left instead of how much has passed. Even though <code>Dot -1</code> and <code>Dot 9</code> are synonymous <code>Declock</code> times, the former could highlight that there is only 1 tenth (⅒ or .1) of the day remaining before midnight. <code>Dot 5</code> and <code>Dot -5</code> both mean noon, like saying that a glass is half-empty or half-full.</p>
<p>The <code>.y</code> format can include positive and negative numbers, most commonly in the form <code>±year±day.day±z</code>, where <code>.day</code> is the time and <code>z</code> is the time zone. The year is usually provided without a sign, because most people rarely discuss years before 1 BCE. The other two signs are required in written form, but plus signs can be omitted when speaking. For example, the <code>stamp</code> <code>2000+000.500+0</code> is pronounced “<code>Year 2000 Day 0 Dot 500 Zone 0</code>” or “<code>2000 0 500 0</code>”, while <code>2000-366.600-1</code> (the same <code>stamp</code> in negative form and in <code>Zone -1</code>) would be said “<code>Year 2000 Day Minus 366 Dot 600 Zone Minus 1</code>” or “<code>2000 -366 600 -1</code>”.</p>
</section>
</section>
<section id="sec-units" class="level2">
<h2 class="anchored" data-anchor-id="sec-units">Units</h2>
<p>In the <code>stamps</code> above, the time has 3 digits, because this is the best level of precision for displaying time on clocks and watches, but times can have any number of digits, depending on the desired precision level. <code>Declock</code> provides names for extremely precise time units, but the most relevant units are within a few orders of magnitude from a day, which is the base unit of both <code>Declock</code> and <code>Decalendar</code>. Listing the units of each highlights the relationship between the two:</p>
<div id="tbl-units" class="anchored">
<table class="table">
<caption>Table&nbsp;4: The units of <code>Decalendar</code> and <code>Declock</code></caption>
<thead>
<tr class="header">
<th>Base 10</th>
<th>Name</th>
<th>Symbol</th>
<th>Formal Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10²</td>
<td><code>hekt</code></td>
<td>ρ</td>
<td><code>hectoday</code></td>
</tr>
<tr class="even">
<td>9.1 x 10¹</td>
<td><code>delt</code></td>
<td>δ</td>
<td><code>deltayear</code></td>
</tr>
<tr class="odd">
<td>9 x 10¹</td>
<td><code>qop</code></td>
<td>ϟ</td>
<td><code>qoppaday</code></td>
</tr>
<tr class="even">
<td>8 x 10¹</td>
<td><code>pi</code></td>
<td>π</td>
<td><code>piday</code></td>
</tr>
<tr class="odd">
<td>7.3 x 10¹</td>
<td><code>ep</code></td>
<td>ε</td>
<td><code>epsilonyear</code></td>
</tr>
<tr class="even">
<td>7 x 10¹</td>
<td><code>om</code></td>
<td>ο</td>
<td><code>omicronday</code></td>
</tr>
<tr class="odd">
<td>6.1 x 10¹</td>
<td><code>wau</code></td>
<td>ϛ</td>
<td><code>wauyear</code></td>
</tr>
<tr class="even">
<td>6 x 10¹</td>
<td><code>xi</code></td>
<td>ξ</td>
<td><code>xiday</code></td>
</tr>
<tr class="odd">
<td>5 x 10¹</td>
<td><code>nu</code></td>
<td>ν</td>
<td><code>nuday</code></td>
</tr>
<tr class="even">
<td>4 x 10¹</td>
<td><code>mu</code></td>
<td>Μ</td>
<td><code>muday</code></td>
</tr>
<tr class="odd">
<td>3 x 10¹</td>
<td><code>lam</code></td>
<td>λ</td>
<td><code>lamdaday</code></td>
</tr>
<tr class="even">
<td>2 x 10¹</td>
<td><code>kap</code></td>
<td>κ</td>
<td><code>kappaday</code></td>
</tr>
<tr class="odd">
<td>10¹</td>
<td><code>dek</code></td>
<td>ι, 旬</td>
<td><code>decaday</code></td>
</tr>
<tr class="even">
<td>10⁰</td>
<td><code>day</code></td>
<td>d, 日</td>
<td><code>day</code></td>
</tr>
<tr class="odd">
<td>10⁻¹</td>
<td><code>dime</code></td>
<td>⅒, 更</td>
<td><code>deciday</code></td>
</tr>
<tr class="even">
<td>10⁻²</td>
<td><code>cent</code></td>
<td>¢, %</td>
<td><code>centiday</code></td>
</tr>
<tr class="odd">
<td>10⁻³</td>
<td><code>mil</code></td>
<td>m, ‰</td>
<td><code>milliday</code></td>
</tr>
<tr class="even">
<td>2 x 10⁻⁴</td>
<td><code>period</code></td>
<td>.</td>
<td><code>didecimilliday</code></td>
</tr>
<tr class="odd">
<td>10⁻⁴</td>
<td><code>phrase</code></td>
<td>̑, ‱</td>
<td><code>decimilliday</code></td>
</tr>
<tr class="even">
<td>2 x 10⁻⁵</td>
<td><code>bar</code></td>
<td>|</td>
<td><code>dicentimilliday</code></td>
</tr>
<tr class="odd">
<td>10⁻⁵</td>
<td><code>beat</code></td>
<td>♫</td>
<td><code>centimilliday</code></td>
</tr>
<tr class="even">
<td>10⁻⁶</td>
<td><code>mic</code></td>
<td>μ</td>
<td><code>microday</code></td>
</tr>
<tr class="odd">
<td>10⁻⁷</td>
<td><code>liph</code></td>
<td>m̑</td>
<td><code>decimicroday</code></td>
</tr>
<tr class="even">
<td>10⁻⁸</td>
<td><code>lib</code></td>
<td>m̈</td>
<td><code>centimicroday</code></td>
</tr>
<tr class="odd">
<td>10⁻⁹</td>
<td><code>nan</code></td>
<td>n</td>
<td><code>nanoday</code></td>
</tr>
<tr class="even">
<td>10⁻¹⁰</td>
<td><code>roph</code></td>
<td>μ̑</td>
<td><code>decinanoday</code></td>
</tr>
<tr class="odd">
<td>10⁻¹¹</td>
<td><code>rob</code></td>
<td>µ̈</td>
<td><code>centinanoday</code></td>
</tr>
<tr class="even">
<td>10⁻¹²</td>
<td><code>pic</code></td>
<td>p</td>
<td><code>picoday</code></td>
</tr>
<tr class="odd">
<td>10⁻¹³</td>
<td><code>noph</code></td>
<td>n̑</td>
<td><code>decipicoday</code></td>
</tr>
<tr class="even">
<td>10⁻¹⁴</td>
<td><code>nob</code></td>
<td>n̊</td>
<td><code>centipicoday</code></td>
</tr>
<tr class="odd">
<td>10⁻¹⁵</td>
<td><code>femt</code></td>
<td>f</td>
<td><code>femtoday</code></td>
</tr>
<tr class="even">
<td>10⁻¹⁶</td>
<td><code>coph</code></td>
<td>p̑</td>
<td><code>decifemtoday</code></td>
</tr>
<tr class="odd">
<td>10⁻¹⁷</td>
<td><code>cob</code></td>
<td>p̈</td>
<td><code>centifemtoday</code></td>
</tr>
<tr class="even">
<td>10⁻¹⁸</td>
<td><code>att</code></td>
<td>a</td>
<td><code>attoday</code></td>
</tr>
<tr class="odd">
<td>10⁻¹⁹</td>
<td><code>foph</code></td>
<td>f̑</td>
<td><code>deciattoday</code></td>
</tr>
<tr class="even">
<td>10⁻²⁰</td>
<td><code>fob</code></td>
<td>f̈</td>
<td><code>centiattoday</code></td>
</tr>
<tr class="odd">
<td>10⁻²¹</td>
<td><code>zept</code></td>
<td>z</td>
<td><code>zeptoday</code></td>
</tr>
<tr class="even">
<td>10⁻²²</td>
<td><code>toph</code></td>
<td>ȃ</td>
<td><code>decizeptoday</code></td>
</tr>
<tr class="odd">
<td>10⁻²³</td>
<td><code>tob</code></td>
<td>ä</td>
<td><code>centizeptoday</code></td>
</tr>
<tr class="even">
<td>10⁻²⁴</td>
<td><code>yokt</code></td>
<td>y</td>
<td><code>yoctoday</code></td>
</tr>
<tr class="odd">
<td>10⁻²⁵</td>
<td><code>zoph</code></td>
<td>z̑</td>
<td><code>deciyoctoday</code></td>
</tr>
<tr class="even">
<td>10⁻²⁶</td>
<td><code>zob</code></td>
<td>z̈</td>
<td><code>centiyoctoday</code></td>
</tr>
<tr class="odd">
<td>10⁻²⁷</td>
<td><code>ront</code></td>
<td>r</td>
<td><code>rontoday</code></td>
</tr>
<tr class="even">
<td>10⁻²⁸</td>
<td><code>yoph</code></td>
<td>y̑</td>
<td><code>decirontoday</code></td>
</tr>
<tr class="odd">
<td>10⁻²⁹</td>
<td><code>yob</code></td>
<td>ẙ</td>
<td><code>centirontoday</code></td>
</tr>
<tr class="even">
<td>10⁻³⁰</td>
<td><code>quek</code></td>
<td>q</td>
<td><code>quectoday</code></td>
</tr>
</tbody>
</table>
</div>
<p>In the table above, the units with positive exponents are used for <code>Decalendar</code>, while the ones with negative exponents are used for <code>Declock</code>. <code>Cents</code> (<code>¢</code>) can serve as a useful point of comparison to understand the scale of some of the units in the table above, because each <code>cent</code> is 1 percent of the day, which is about a quarter hour (1% = 14.4 minutes). In comparison to <code>cents</code>, <code>mils</code> are ten times smaller (.1% = 1.4 minutes), <code>dimes</code> (<code>⅒</code>) are ten times larger (10% = 144 minutes), and <code>deks</code> (<code>ι</code>) are 1000 times larger (1000% = 14400 minutes). To be clear, 1 <code>dek</code> contains 10 whole days while the other units are fractions of days.</p>
<p><code>Declock</code> units smaller than <code>mils</code> are not easy to think of as percents of a day. For <code>phrases</code> (<code>̑</code>) and <code>beats</code> (<code>♫</code>), music serves as a much more useful analogy. In fact, <code>phrases</code> and <code>beats</code> are musical terms. The duration of a musical beat depends on the tempo, but a <code>Declock beat</code> is always precisely 0.864 seconds long. This translates to a tempo of 69.4̅ (69⁴/₉ or 625/9) beats per minute, which is coincidentally also within the normal range of a resting heart rate. <code>Declock beats</code> are organized into groups of 2 called <code>bars</code> or <code>measures</code>, groups of 10 called <code>phrases</code>, and groups of 20 called <code>periods</code>. A real example of music that follows this exact pattern is Haydn’s <a href="https://en.wikipedia.org/wiki/Period_(music)">Feldpartita</a>.</p>
<p><code>Declock</code> units smaller than <code>beats</code> are too small for typical daily use. For example, a <code>mic</code> (<code>microday</code>, <code>μ</code>) is faster than a blink of an eye. Each frame in a video playing at 60 frames per second will be shown for about 1.93 <code>liphs</code> (<code>milliphrases</code>, <code>m̑</code>). A <code>lib</code> (<code>millibeat</code>, <code>m̈</code>) is not enough time for a neuron in a human brain to fire and return to rest. Sound can travel from a person’s ear to their other ear in about 7 <code>nans</code> (<code>nanodays</code>). Noticing that a sound reaches one ear before the other can help humans to localize the source of the sound, but a <code>roph</code> (<code>microphrase</code>, <code>μ̑</code>) difference might be too fast to notice. In a <code>rob</code> (<code>microbeat</code>, <code>µ̈</code>), a USB 3.0 cable transferring 5 gigabytes per second can send 4.32 kilobytes, the equivalent of a text file with 4320 characters.</p>
<section id="sec-zones" class="level3">
<h3 class="anchored" data-anchor-id="sec-zones">Time Zones</h3>
<p>Of the units discussed above, <code>dimes</code> are notable, because they are the units of <code>Declock</code> time zones. The times in <code>Zone 1</code> are one <code>dime</code> later than <code>Zone 0</code> and two <code>dimes</code> later than <code>Zone -1</code>. Time zones are important, because different time zones could have very different times and even different dates. Mexico City is in <code>Zone -3</code> and Tokyo is in <code>Zone 4</code>, meaning for the majority of the day (<code>Dot 7</code> to be exact) Tokyo is one day ahead of Mexico City. If it is noon on the last day of the year 1999 in Mexico City, it will be <code>Dot 200</code> on the first day of the year 2000 in Tokyo. This date and time in Mexico City can be written <code>2000+000.200+4</code> or <code>2000-365.800+4</code>, while the equivalent date and time for Tokyo is <code>1999+365.500-3</code> or <code>1999-001.500-3</code>. If we removed the time zone from the end, we would not know that all of these <code>stamps</code> describe the same moment in time.</p>
</section>
<section id="sec-formats" class="level3">
<h3 class="anchored" data-anchor-id="sec-formats">The Dot Formats</h3>
<p>The <code>stamps</code> shown above are in the decimal days of the year (<code>.y</code>) format, which is the main <code>Decalendar</code> format. In addition to the <code>.y</code> format, there are 2 other supplemental <code>datetime</code> formats, which are based on decimal days of the month (<code>.m</code>), and decimal days of the week (<code>.w</code>). The table below summarizes the three decimal day-of-the ( <code>dot</code> or <code>.</code>) formats:</p>
<div id="tbl-formats" class="anchored">
<table class="table">
<caption>Table&nbsp;5: The three dot formats</caption>
<thead>
<tr class="header">
<th>Day of the</th>
<th><code>.</code></th>
<th>General Form</th>
<th>Specific Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Year</td>
<td><code>y</code></td>
<td><code>year±day.day±z</code></td>
<td><code>1999+365.500-3</code></td>
</tr>
<tr class="even">
<td>Month</td>
<td><code>m</code></td>
<td><code>year±m±dd.day±z</code></td>
<td><code>1999+B+29.500-3</code></td>
</tr>
<tr class="odd">
<td>Week</td>
<td><code>w</code></td>
<td><code>year±ww±d.day±z</code></td>
<td><code>1999+52+5.500-3</code></td>
</tr>
</tbody>
</table>
</div>
<p>In the table above, <code>day</code> is the 3-digit day of the year (<code>doty</code>) number, <code>dd</code> is the 2-digit day of the month (<code>dotm</code>) number, <code>d</code> is the 1-digit day of the week (<code>dotw</code>) number, and <code>.day</code> is the time in <code>mils</code>.</p>
</section>
<section id="sec-dotm" class="level3">
<h3 class="anchored" data-anchor-id="sec-dotm">The <code>.m</code> format</h3>
<p>The <code>m</code> in the <code>.m</code> format is the 1-digit month number. To fit all of the months in a single digit, <code>m</code> is in hexadecimal form (Base16 encoded). This means that the first 10 months are represented by the numbers 0 through 9 while the last two months of the year are represented by the letters “A” and “B” instead of numbers. The negative month numbers range from -C (-13) to -1, as shown in the first table: <a href="#tbl-mvals">Table&nbsp;1</a>.</p>
</section>
<section id="sec-dotw" class="level3">
<h3 class="anchored" data-anchor-id="sec-dotw">The <code>.w</code> format</h3>
<p>The week number in the <code>.w</code> format, <code>ww</code>, ranges from 0 to 53 or -54 to -1. Weeks in the <code>.w</code> format start from Sunday. The table below shows the possible <code>dotw</code> values, which range from 0 to 6 or -7 to -1.</p>
<div id="tbl-dotw" class="anchored">
<table class="table">
<caption>Table&nbsp;6: The weeks in the <code>.w</code> format</caption>
<thead>
<tr class="header">
<th>Day</th>
<th>Pos</th>
<th>Neg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sunday</td>
<td>0</td>
<td>-7</td>
</tr>
<tr class="even">
<td>Monday</td>
<td>1</td>
<td>-6</td>
</tr>
<tr class="odd">
<td>Tuesday</td>
<td>2</td>
<td>-5</td>
</tr>
<tr class="even">
<td>Wednesday</td>
<td>3</td>
<td>-4</td>
</tr>
<tr class="odd">
<td>Thursday</td>
<td>4</td>
<td>-3</td>
</tr>
<tr class="even">
<td>Friday</td>
<td>5</td>
<td>-2</td>
</tr>
<tr class="odd">
<td>Saturday</td>
<td>6</td>
<td>-1</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-dotex" class="level3">
<h3 class="anchored" data-anchor-id="sec-dotex"><code>.</code> format examples</h3>
<p>The table below builds on the example from the <a href="#Time-Zones">“Time Zones” section</a> section to compare all three <code>.</code> formats. The 3 <code>.</code> formats differ only in their approach to the date, not the time. Therefore, the times below are all shown to 1-digit <code>dime</code> precision (same as time zones) instead of the typical 3-digit <code>mil</code> precision. In Mexico City, the time is <code>+5-3</code> or <code>-5-3</code>, while the time in London is <code>+8+0</code> or <code>-2+0</code> and time in Tokyo is <code>+2+4</code> or <code>-8+4</code>.</p>
<div id="tbl-dotex" class="anchored">
<table class="table">
<caption>Table&nbsp;7: The time in Mexico City, London, and Tokyo in all three dot formats</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Day of the</th>
<th><code>.</code></th>
<th>Mexico City</th>
<th>London</th>
<th>Tokyo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Year</td>
<td><code>y</code></td>
<td><code>1999+365.5-3</code></td>
<td><code>1999+365.8-3</code></td>
<td><code>2000+000.2+4</code></td>
</tr>
<tr class="even">
<td>Year</td>
<td><code>y</code></td>
<td><code>1999-001.5-3</code></td>
<td><code>1999-001.2-3</code></td>
<td><code>2000-365.8+4</code></td>
</tr>
<tr class="odd">
<td>Month</td>
<td><code>m</code></td>
<td><code>1999+B+29.5-3</code></td>
<td><code>1999+B+29.8-3</code></td>
<td><code>2000+0+00.2+4</code></td>
</tr>
<tr class="even">
<td>Month</td>
<td><code>m</code></td>
<td><code>1999-1-01.5-3</code></td>
<td><code>1999-1-01.2-3</code></td>
<td><code>2000-C-31.8+4</code></td>
</tr>
<tr class="odd">
<td>Week</td>
<td><code>w</code></td>
<td><code>1999+52+2.5-3</code></td>
<td><code>1999+52+2.8-3</code></td>
<td><code>2000+00+3.2+4</code></td>
</tr>
<tr class="even">
<td>Week</td>
<td><code>w</code></td>
<td><code>1999-01-5.5-3</code></td>
<td><code>1999-01-5.2-3</code></td>
<td><code>2000-53-4.8+4</code></td>
</tr>
</tbody>
</table>
</div>
<p>In the table above, the <code>.m</code> format tells us that the month in Tokyo is January (<code>Month 0</code>) and the month in Mexico City and London is December (<code>Month B</code>). We could say the <code>.m</code> dates in Mexico City and London as “<code>Year 1999 Month B Day 29</code>” or “<code>Year 1999 Month -1 Day -1</code>” and the Tokyo date as “<code>Year 2000 Month 0 Day 0</code>” or” <code>Year 2000 Month -C Day -31</code>“.</p>
<p>The <code>.w</code> format always starts the year with <code>Week 0</code>, but the year can start on any day of the week. The table above shows that the year 2000 starts on a Saturday (<code>Week 0 Day 6</code>). The <code>.w</code> dates in Mexico City and London could be said “<code>Year 1999 Week 52 Day 2</code>” or “<code>Year 1999 Week -1 Day -5</code>”, while the date in Tokyo could be pronounced “<code>Year 2000 Week 0 Day 3</code>” or “<code>Year 2000 Week -52 Day -4</code>” in Tokyo.</p>
<p>In contrast to the <code>.m</code> and the <code>.w</code> formats, the dates in the <code>.y</code> format are one character shorter and a little easier to say. The spoken form of the <code>.y</code> date in Mexico City and London is “<code>Year 1999 Day 365</code>” or “<code>Year 1999 Day -1</code>” and the spoken form of the Tokyo date is “<code>Year 2000 Day 0</code>” or “<code>Year 2000 Day -365</code>”.</p>
</section>
<section id="sec-deks" class="level3">
<h3 class="anchored" data-anchor-id="sec-deks"><code>Deks</code></h3>
<p>Even though it provides formats for months and weeks, <code>Decalendar</code> envisions a world in which these units are replaced by <code>deks</code>. In terms of scale, <code>deks</code> are somewhere between a week and a month, precisely half a day less than a week and a half (1.5 weeks - 0.5 days) and approximately a third of month. <code>Deks</code> could provide the functionality of both weeks and months if we followed a <code>dekly</code> schedule instead of <code>weekly</code> and <code>monthly</code> schedules. The transition to a <code>dekly</code> schedule would be a massive undertaking, but could start with the creation of the digital infrastructure needed for the new system. Every desktop and mobile application that uses dates could be adapted to optionally use <code>deks</code> instead of weeks and months.</p>
<section id="sec-dotd" class="level4">
<h4 class="anchored" data-anchor-id="sec-dotd">Days of the <code>dek</code></h4>
<p>A major difficulty with the Gregorian calendar is that the date is disconnected from the day of the week. In contrast, the day of the <code>dek</code> (<code>dotd</code>) is simply the last digit of the day number in the <code>.y</code> format. For example, the first day of the year (<code>Day 0</code>) is always an <code>Nulday</code>, the last day of common years (<code>Day 364</code>) is always an <code>Quaday</code>, and the last day of leap years (<code>Day 365</code>) is always a <code>Penday</code>. The day number allows us to distinguish workdays from restdays. <code>Decalendar</code> defines <code>Triday</code>, <code>Quaday</code>, <code>Octday</code>, and <code>Ennday</code> as restdays, which means that days with numbers that end in 3, 4, 8, or 9 are days off from work and school. Each <code>dek</code> consists of 2 <code>pents</code> (<code>pentadays</code>), each <code>pent</code> has 3 workdays called the <code>trep</code> (<code>trepalium</code>) and 2 restdays called the <code>pentend</code>. In total, there are 219 workdays and 146 restdays in a <code>Decalendar</code> year, not counting the only obligatory holiday, Leap Day (<code>Day 365</code>).</p>
</section>
<section id="sec-work" class="level4">
<h4 class="anchored" data-anchor-id="sec-work">Workdays</h4>
<p>The Gregorian calendar has many more workdays, 260 in common years and 261 in leap year. Despite having many fewer workdays and many more restdays, workers following <code>Decalendar</code> would actually spent slightly more time at work overall, because the <code>Decalendar</code> workday goes from <code>Dot 3</code> to <code>Dot 7</code> and thus is 4 <code>dimes</code> (9.6 hours) long, 6.6̅ <code>cents</code> (96 minutes) longer than the typical 9-to-5 work schedule (<code>Dot 375</code> to <code>Dot 7083̅</code>). In other words, this work schedule starts 75 <code>mils</code> (1.8 hours) earlier than 9AM (<code>Dot 375</code>) and ends 8.3̅ <code>mils</code> (12 minutes) earlier than 5PM (<code>Dot 7083̅</code>). In a typical 40-hour workweek, workers spend 23.80952381 <code>cents</code> per day at work on average, which adds up to 8.6̅ <code>deks</code> (260<em>8/240) per common year and 8.7 <code>deks</code> (261</em>8/240) per leap year. In contrast, workers following <code>Decalendar</code> spend 24 <code>cents</code> per day at work on average, which totals up to 8.76 <code>deks</code> (219*.04) spent at work every year. The default approach of <code>Decalendar</code> is to compensate for having more restdays with longer workdays.</p>
</section>
<section id="sec-sched" class="level4">
<h4 class="anchored" data-anchor-id="sec-sched">Schedules</h4>
<section id="sec-pently" class="level5">
<h5 class="anchored" data-anchor-id="sec-pently">Pently schedules</h5>
<p>If necessary, the length of the workday and the number of workdays in the <code>dek</code> can be adjusted according to different schedules. As mentioned above, each half of the <code>dek</code> is called a <code>pent</code>. Each <code>pent</code> can have its own <code>pently</code> schedule. The expectation is that workers will work for 12 <code>dimes</code> per <code>pent</code>. It is possible to split those 12 <code>dimes</code> over the course of 5, 4, 3, or 2 days in each <code>pent</code>. The table below displays how the number of workdays and restdays in a <code>pent</code> affects the start time, end time, and duration of the workday. The different <code>pently</code> schedules are named after the number of workdays per <code>pent</code>. People can switch between <code>pently</code> schedules every <code>pent</code> as needed, but unless there is a compelling reason to follow a different <code>pently</code> schedule, everyone should follow the <code>Schedule 3</code> by default. <code>Schedule 3</code> has 3 workdays and 2 restdays in each <code>pent</code>. Each <code>Schedule 3</code> workday starts at <code>Dot 3</code>, ends at <code>Dot 7</code>, and lasts 4 <code>dimes</code>.</p>
<div id="tbl-pently" class="anchored">
<table class="table">
<caption>Table&nbsp;8: The characteristics of the pently schedules</caption>
<thead>
<tr class="header">
<th>Schedule</th>
<th>Workdays</th>
<th>Restdays</th>
<th>Start</th>
<th>End</th>
<th>Duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>2</td>
<td>3</td>
<td>.2</td>
<td>.8</td>
<td>.6</td>
</tr>
<tr class="even">
<td>3</td>
<td>3</td>
<td>2</td>
<td>.3</td>
<td>.7</td>
<td>.4</td>
</tr>
<tr class="odd">
<td>4</td>
<td>4</td>
<td>1</td>
<td>.35</td>
<td>.65</td>
<td>.3</td>
</tr>
<tr class="even">
<td>5</td>
<td>5</td>
<td>0</td>
<td>.38</td>
<td>.62</td>
<td>.24</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-daily" class="level5">
<h5 class="anchored" data-anchor-id="sec-daily">Daily schedules</h5>
<p><code>Decalendar</code> recommends waking up at <code>Dot 2</code> and going to bed at <code>Dot 8</code>. This recommendation allots 4 <code>dimes</code> (9.6 hours) for falling asleep and sleeping. To keep daily schedules symmetrical, the time spent awake should be split evenly before and after work. People following <code>Schedule 3</code> would thus have 10 <code>cents</code> (2.4 hours) to prepare for work and another 10 <code>cents</code> to prepare for bed. The table below shows the recommended <code>Schedule 3</code> daily schedule. <code>Schedule 4</code> and <code>Schedule 5</code> allot even more time, 15 <code>cents</code> (3.6 hours) and 18 <code>cents</code> (4.32 hours), respectively, for before-work and after-work activities. The recommended sleep schedule does not fit well with <code>Schedule 2</code>, but this incompatibility does not have to result in a sleep deficit. If the <code>Schedule 2</code> workdays are not consecutive, people following <code>Schedule 2</code> can catch up on sleep on their days off by going to bed early before and sleeping in after every workday.</p>
<div id="tbl-daily" class="anchored">
<table class="table">
<caption>Table&nbsp;9: The workday schedule</caption>
<thead>
<tr class="header">
<th>Start</th>
<th>End</th>
<th>Duration</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.2</td>
<td>.3</td>
<td>.1</td>
<td>Wake up and prepare for work</td>
</tr>
<tr class="even">
<td>.3</td>
<td>.7</td>
<td>.4</td>
<td>Work</td>
</tr>
<tr class="odd">
<td>.7</td>
<td>.8</td>
<td>.1</td>
<td>End work and prepare for bed</td>
</tr>
<tr class="even">
<td>.8</td>
<td>.2</td>
<td>.4</td>
<td>Go to bed and sleep</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="sec-coor" class="level4">
<h4 class="anchored" data-anchor-id="sec-coor">Coordinate analogy</h4>
<p>In the Gregorian calendar, dates are like a set of coordinates, where the month and the day of the month (<code>dotm</code>) are like longitude and latitude in the Geographic coordinate system or x and y in the Cartesian coordinate system. <code>Decalendar</code> provides both coordinates in one number, the <code>doty</code> contains both the <code>dek</code> number (first 2 digits) and the <code>dotd</code> number (last digit). In this way, the <code>doty</code> contains all of the information we need for the <code>Decalendar</code> system: the <code>dek</code>, which fulfills the role of both the month and the week, and the <code>dotd</code>, which fulfills the role of both the day of the month and the day of the week.</p>
</section>
<section id="sec-conv" class="level4">
<h4 class="anchored" data-anchor-id="sec-conv">Conversion tables</h4>
<section id="sec-specific" class="level5">
<h5 class="anchored" data-anchor-id="sec-specific">Common and leap year specific conversion tables</h5>
<p>The first table below shows the positive <code>doty</code> numbers for all Gregorian calendar dates. Negative <code>doty</code> numbers require two separate tables for common and leap years. In all of these tables, the columns are labeled by month (like longitudes or x-axis values), while the rows are labeled by the day of the month (like latitudes or y-axis values). Since the <code>Decalendar</code> leap day is at the end of the year and everything resets after the end of each year, <code>Decalendar</code> leap days do not affect the positive <code>doty</code> numbers of any other <code>Decalendar</code> days.</p>
<div id="tbl-conv" class="anchored">
<table class="table">
<caption>Table&nbsp;10: Gregorian calendar date to positive <code>doty</code> conversion</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Day</th>
<th>Mar</th>
<th>Apr</th>
<th>May</th>
<th>Jun</th>
<th>Jul</th>
<th>Aug</th>
<th>Sep</th>
<th>Oct</th>
<th>Nov</th>
<th>Dec</th>
<th>Jan</th>
<th>Feb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>31</td>
<td>61</td>
<td>92</td>
<td>122</td>
<td>153</td>
<td>184</td>
<td>214</td>
<td>245</td>
<td>275</td>
<td>306</td>
<td>337</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>32</td>
<td>62</td>
<td>93</td>
<td>123</td>
<td>154</td>
<td>185</td>
<td>215</td>
<td>246</td>
<td>276</td>
<td>307</td>
<td>338</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2</td>
<td>33</td>
<td>63</td>
<td>94</td>
<td>124</td>
<td>155</td>
<td>186</td>
<td>216</td>
<td>247</td>
<td>277</td>
<td>308</td>
<td>339</td>
</tr>
<tr class="even">
<td>4</td>
<td>3</td>
<td>34</td>
<td>64</td>
<td>95</td>
<td>125</td>
<td>156</td>
<td>187</td>
<td>217</td>
<td>248</td>
<td>278</td>
<td>309</td>
<td>340</td>
</tr>
<tr class="odd">
<td>5</td>
<td>4</td>
<td>35</td>
<td>65</td>
<td>96</td>
<td>126</td>
<td>157</td>
<td>188</td>
<td>218</td>
<td>249</td>
<td>279</td>
<td>310</td>
<td>341</td>
</tr>
<tr class="even">
<td>6</td>
<td>5</td>
<td>36</td>
<td>66</td>
<td>97</td>
<td>127</td>
<td>158</td>
<td>189</td>
<td>219</td>
<td>250</td>
<td>280</td>
<td>311</td>
<td>342</td>
</tr>
<tr class="odd">
<td>7</td>
<td>6</td>
<td>37</td>
<td>67</td>
<td>98</td>
<td>128</td>
<td>159</td>
<td>190</td>
<td>220</td>
<td>251</td>
<td>281</td>
<td>312</td>
<td>343</td>
</tr>
<tr class="even">
<td>8</td>
<td>7</td>
<td>38</td>
<td>68</td>
<td>99</td>
<td>129</td>
<td>160</td>
<td>191</td>
<td>221</td>
<td>252</td>
<td>282</td>
<td>313</td>
<td>344</td>
</tr>
<tr class="odd">
<td>9</td>
<td>8</td>
<td>39</td>
<td>69</td>
<td>100</td>
<td>130</td>
<td>161</td>
<td>192</td>
<td>222</td>
<td>253</td>
<td>283</td>
<td>314</td>
<td>345</td>
</tr>
<tr class="even">
<td>10</td>
<td>9</td>
<td>40</td>
<td>70</td>
<td>101</td>
<td>131</td>
<td>162</td>
<td>193</td>
<td>223</td>
<td>254</td>
<td>284</td>
<td>315</td>
<td>346</td>
</tr>
<tr class="odd">
<td>11</td>
<td>10</td>
<td>41</td>
<td>71</td>
<td>102</td>
<td>132</td>
<td>163</td>
<td>194</td>
<td>224</td>
<td>255</td>
<td>285</td>
<td>316</td>
<td>347</td>
</tr>
<tr class="even">
<td>12</td>
<td>11</td>
<td>42</td>
<td>72</td>
<td>103</td>
<td>133</td>
<td>164</td>
<td>195</td>
<td>225</td>
<td>256</td>
<td>286</td>
<td>317</td>
<td>348</td>
</tr>
<tr class="odd">
<td>13</td>
<td>12</td>
<td>43</td>
<td>73</td>
<td>104</td>
<td>134</td>
<td>165</td>
<td>196</td>
<td>226</td>
<td>257</td>
<td>287</td>
<td>318</td>
<td>349</td>
</tr>
<tr class="even">
<td>14</td>
<td>13</td>
<td>44</td>
<td>74</td>
<td>105</td>
<td>135</td>
<td>166</td>
<td>197</td>
<td>227</td>
<td>258</td>
<td>288</td>
<td>319</td>
<td>350</td>
</tr>
<tr class="odd">
<td>15</td>
<td>14</td>
<td>45</td>
<td>75</td>
<td>106</td>
<td>136</td>
<td>167</td>
<td>198</td>
<td>228</td>
<td>259</td>
<td>289</td>
<td>320</td>
<td>351</td>
</tr>
<tr class="even">
<td>16</td>
<td>15</td>
<td>46</td>
<td>76</td>
<td>107</td>
<td>137</td>
<td>168</td>
<td>199</td>
<td>229</td>
<td>260</td>
<td>290</td>
<td>321</td>
<td>352</td>
</tr>
<tr class="odd">
<td>17</td>
<td>16</td>
<td>47</td>
<td>77</td>
<td>108</td>
<td>138</td>
<td>169</td>
<td>200</td>
<td>230</td>
<td>261</td>
<td>291</td>
<td>322</td>
<td>353</td>
</tr>
<tr class="even">
<td>18</td>
<td>17</td>
<td>48</td>
<td>78</td>
<td>109</td>
<td>139</td>
<td>170</td>
<td>201</td>
<td>231</td>
<td>262</td>
<td>292</td>
<td>323</td>
<td>354</td>
</tr>
<tr class="odd">
<td>19</td>
<td>18</td>
<td>49</td>
<td>79</td>
<td>110</td>
<td>140</td>
<td>171</td>
<td>202</td>
<td>232</td>
<td>263</td>
<td>293</td>
<td>324</td>
<td>355</td>
</tr>
<tr class="even">
<td>20</td>
<td>19</td>
<td>50</td>
<td>80</td>
<td>111</td>
<td>141</td>
<td>172</td>
<td>203</td>
<td>233</td>
<td>264</td>
<td>294</td>
<td>325</td>
<td>356</td>
</tr>
<tr class="odd">
<td>21</td>
<td>20</td>
<td>51</td>
<td>81</td>
<td>112</td>
<td>142</td>
<td>173</td>
<td>204</td>
<td>234</td>
<td>265</td>
<td>295</td>
<td>326</td>
<td>357</td>
</tr>
<tr class="even">
<td>22</td>
<td>21</td>
<td>52</td>
<td>82</td>
<td>113</td>
<td>143</td>
<td>174</td>
<td>205</td>
<td>235</td>
<td>266</td>
<td>296</td>
<td>327</td>
<td>358</td>
</tr>
<tr class="odd">
<td>23</td>
<td>22</td>
<td>53</td>
<td>83</td>
<td>114</td>
<td>144</td>
<td>175</td>
<td>206</td>
<td>236</td>
<td>267</td>
<td>297</td>
<td>328</td>
<td>359</td>
</tr>
<tr class="even">
<td>24</td>
<td>23</td>
<td>54</td>
<td>84</td>
<td>115</td>
<td>145</td>
<td>176</td>
<td>207</td>
<td>237</td>
<td>268</td>
<td>298</td>
<td>329</td>
<td>360</td>
</tr>
<tr class="odd">
<td>25</td>
<td>24</td>
<td>55</td>
<td>85</td>
<td>116</td>
<td>146</td>
<td>177</td>
<td>208</td>
<td>238</td>
<td>269</td>
<td>299</td>
<td>330</td>
<td>361</td>
</tr>
<tr class="even">
<td>26</td>
<td>25</td>
<td>56</td>
<td>86</td>
<td>117</td>
<td>147</td>
<td>178</td>
<td>209</td>
<td>239</td>
<td>270</td>
<td>300</td>
<td>331</td>
<td>362</td>
</tr>
<tr class="odd">
<td>27</td>
<td>26</td>
<td>57</td>
<td>87</td>
<td>118</td>
<td>148</td>
<td>179</td>
<td>210</td>
<td>240</td>
<td>271</td>
<td>301</td>
<td>332</td>
<td>363</td>
</tr>
<tr class="even">
<td>28</td>
<td>27</td>
<td>58</td>
<td>88</td>
<td>119</td>
<td>149</td>
<td>180</td>
<td>211</td>
<td>241</td>
<td>272</td>
<td>302</td>
<td>333</td>
<td>364</td>
</tr>
<tr class="odd">
<td>29</td>
<td>28</td>
<td>59</td>
<td>89</td>
<td>120</td>
<td>150</td>
<td>181</td>
<td>212</td>
<td>242</td>
<td>273</td>
<td>303</td>
<td>334</td>
<td>365</td>
</tr>
<tr class="even">
<td>30</td>
<td>29</td>
<td>60</td>
<td>90</td>
<td>121</td>
<td>151</td>
<td>182</td>
<td>213</td>
<td>243</td>
<td>274</td>
<td>304</td>
<td>335</td>
<td></td>
</tr>
<tr class="odd">
<td>31</td>
<td>30</td>
<td></td>
<td>91</td>
<td></td>
<td>152</td>
<td>183</td>
<td></td>
<td>244</td>
<td></td>
<td>305</td>
<td>336</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-common" class="anchored">
<table class="table">
<caption>Table&nbsp;11: Gregorian calendar date to negative <code>doty</code> common year conversion</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Day</th>
<th>Mar</th>
<th>Apr</th>
<th>May</th>
<th>Jun</th>
<th>Jul</th>
<th>Aug</th>
<th>Sep</th>
<th>Oct</th>
<th>Nov</th>
<th>Dec</th>
<th>Jan</th>
<th>Feb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>-365</td>
<td>-334</td>
<td>-304</td>
<td>-273</td>
<td>-243</td>
<td>-212</td>
<td>-181</td>
<td>-151</td>
<td>-120</td>
<td>-90</td>
<td>-59</td>
<td>-28</td>
</tr>
<tr class="even">
<td>2</td>
<td>-364</td>
<td>-333</td>
<td>-303</td>
<td>-272</td>
<td>-242</td>
<td>-211</td>
<td>-180</td>
<td>-150</td>
<td>-119</td>
<td>-89</td>
<td>-58</td>
<td>-27</td>
</tr>
<tr class="odd">
<td>3</td>
<td>-363</td>
<td>-332</td>
<td>-302</td>
<td>-271</td>
<td>-241</td>
<td>-210</td>
<td>-179</td>
<td>-149</td>
<td>-118</td>
<td>-88</td>
<td>-57</td>
<td>-26</td>
</tr>
<tr class="even">
<td>4</td>
<td>-362</td>
<td>-331</td>
<td>-301</td>
<td>-270</td>
<td>-240</td>
<td>-209</td>
<td>-178</td>
<td>-148</td>
<td>-117</td>
<td>-87</td>
<td>-56</td>
<td>-25</td>
</tr>
<tr class="odd">
<td>5</td>
<td>-361</td>
<td>-330</td>
<td>-300</td>
<td>-269</td>
<td>-239</td>
<td>-208</td>
<td>-177</td>
<td>-147</td>
<td>-116</td>
<td>-86</td>
<td>-55</td>
<td>-24</td>
</tr>
<tr class="even">
<td>6</td>
<td>-360</td>
<td>-329</td>
<td>-299</td>
<td>-268</td>
<td>-238</td>
<td>-207</td>
<td>-176</td>
<td>-146</td>
<td>-115</td>
<td>-85</td>
<td>-54</td>
<td>-23</td>
</tr>
<tr class="odd">
<td>7</td>
<td>-359</td>
<td>-328</td>
<td>-298</td>
<td>-267</td>
<td>-237</td>
<td>-206</td>
<td>-175</td>
<td>-145</td>
<td>-114</td>
<td>-84</td>
<td>-53</td>
<td>-22</td>
</tr>
<tr class="even">
<td>8</td>
<td>-358</td>
<td>-327</td>
<td>-297</td>
<td>-266</td>
<td>-236</td>
<td>-205</td>
<td>-174</td>
<td>-144</td>
<td>-113</td>
<td>-83</td>
<td>-52</td>
<td>-21</td>
</tr>
<tr class="odd">
<td>9</td>
<td>-357</td>
<td>-326</td>
<td>-296</td>
<td>-265</td>
<td>-235</td>
<td>-204</td>
<td>-173</td>
<td>-143</td>
<td>-112</td>
<td>-82</td>
<td>-51</td>
<td>-20</td>
</tr>
<tr class="even">
<td>10</td>
<td>-356</td>
<td>-325</td>
<td>-295</td>
<td>-264</td>
<td>-234</td>
<td>-203</td>
<td>-172</td>
<td>-142</td>
<td>-111</td>
<td>-81</td>
<td>-50</td>
<td>-19</td>
</tr>
<tr class="odd">
<td>11</td>
<td>-355</td>
<td>-324</td>
<td>-294</td>
<td>-263</td>
<td>-233</td>
<td>-202</td>
<td>-171</td>
<td>-141</td>
<td>-110</td>
<td>-80</td>
<td>-49</td>
<td>-18</td>
</tr>
<tr class="even">
<td>12</td>
<td>-354</td>
<td>-323</td>
<td>-293</td>
<td>-262</td>
<td>-232</td>
<td>-201</td>
<td>-170</td>
<td>-140</td>
<td>-109</td>
<td>-79</td>
<td>-48</td>
<td>-17</td>
</tr>
<tr class="odd">
<td>13</td>
<td>-353</td>
<td>-322</td>
<td>-292</td>
<td>-261</td>
<td>-231</td>
<td>-200</td>
<td>-169</td>
<td>-139</td>
<td>-108</td>
<td>-78</td>
<td>-47</td>
<td>-16</td>
</tr>
<tr class="even">
<td>14</td>
<td>-352</td>
<td>-321</td>
<td>-291</td>
<td>-260</td>
<td>-230</td>
<td>-199</td>
<td>-168</td>
<td>-138</td>
<td>-107</td>
<td>-77</td>
<td>-46</td>
<td>-15</td>
</tr>
<tr class="odd">
<td>15</td>
<td>-351</td>
<td>-320</td>
<td>-290</td>
<td>-259</td>
<td>-229</td>
<td>-198</td>
<td>-167</td>
<td>-137</td>
<td>-106</td>
<td>-76</td>
<td>-45</td>
<td>-14</td>
</tr>
<tr class="even">
<td>16</td>
<td>-350</td>
<td>-319</td>
<td>-289</td>
<td>-258</td>
<td>-228</td>
<td>-197</td>
<td>-166</td>
<td>-136</td>
<td>-105</td>
<td>-75</td>
<td>-44</td>
<td>-13</td>
</tr>
<tr class="odd">
<td>17</td>
<td>-349</td>
<td>-318</td>
<td>-288</td>
<td>-257</td>
<td>-227</td>
<td>-196</td>
<td>-165</td>
<td>-135</td>
<td>-104</td>
<td>-74</td>
<td>-43</td>
<td>-12</td>
</tr>
<tr class="even">
<td>18</td>
<td>-348</td>
<td>-317</td>
<td>-287</td>
<td>-256</td>
<td>-226</td>
<td>-195</td>
<td>-164</td>
<td>-134</td>
<td>-103</td>
<td>-73</td>
<td>-42</td>
<td>-11</td>
</tr>
<tr class="odd">
<td>19</td>
<td>-347</td>
<td>-316</td>
<td>-286</td>
<td>-255</td>
<td>-225</td>
<td>-194</td>
<td>-163</td>
<td>-133</td>
<td>-102</td>
<td>-72</td>
<td>-41</td>
<td>-10</td>
</tr>
<tr class="even">
<td>20</td>
<td>-346</td>
<td>-315</td>
<td>-285</td>
<td>-254</td>
<td>-224</td>
<td>-193</td>
<td>-162</td>
<td>-132</td>
<td>-101</td>
<td>-71</td>
<td>-40</td>
<td>-9</td>
</tr>
<tr class="odd">
<td>21</td>
<td>-345</td>
<td>-314</td>
<td>-284</td>
<td>-253</td>
<td>-223</td>
<td>-192</td>
<td>-161</td>
<td>-131</td>
<td>-100</td>
<td>-70</td>
<td>-39</td>
<td>-8</td>
</tr>
<tr class="even">
<td>22</td>
<td>-344</td>
<td>-313</td>
<td>-283</td>
<td>-252</td>
<td>-222</td>
<td>-191</td>
<td>-160</td>
<td>-130</td>
<td>-99</td>
<td>-69</td>
<td>-38</td>
<td>-7</td>
</tr>
<tr class="odd">
<td>23</td>
<td>-343</td>
<td>-312</td>
<td>-282</td>
<td>-251</td>
<td>-221</td>
<td>-190</td>
<td>-159</td>
<td>-129</td>
<td>-98</td>
<td>-68</td>
<td>-37</td>
<td>-6</td>
</tr>
<tr class="even">
<td>24</td>
<td>-342</td>
<td>-311</td>
<td>-281</td>
<td>-250</td>
<td>-220</td>
<td>-189</td>
<td>-158</td>
<td>-128</td>
<td>-97</td>
<td>-67</td>
<td>-36</td>
<td>-5</td>
</tr>
<tr class="odd">
<td>25</td>
<td>-341</td>
<td>-310</td>
<td>-280</td>
<td>-249</td>
<td>-219</td>
<td>-188</td>
<td>-157</td>
<td>-127</td>
<td>-96</td>
<td>-66</td>
<td>-35</td>
<td>-4</td>
</tr>
<tr class="even">
<td>26</td>
<td>-340</td>
<td>-309</td>
<td>-279</td>
<td>-248</td>
<td>-218</td>
<td>-187</td>
<td>-156</td>
<td>-126</td>
<td>-95</td>
<td>-65</td>
<td>-34</td>
<td>-3</td>
</tr>
<tr class="odd">
<td>27</td>
<td>-339</td>
<td>-308</td>
<td>-278</td>
<td>-247</td>
<td>-217</td>
<td>-186</td>
<td>-155</td>
<td>-125</td>
<td>-94</td>
<td>-64</td>
<td>-33</td>
<td>-2</td>
</tr>
<tr class="even">
<td>28</td>
<td>-338</td>
<td>-307</td>
<td>-277</td>
<td>-246</td>
<td>-216</td>
<td>-185</td>
<td>-154</td>
<td>-124</td>
<td>-93</td>
<td>-63</td>
<td>-32</td>
<td>-1</td>
</tr>
<tr class="odd">
<td>29</td>
<td>-337</td>
<td>-306</td>
<td>-276</td>
<td>-245</td>
<td>-215</td>
<td>-184</td>
<td>-153</td>
<td>-123</td>
<td>-92</td>
<td>-62</td>
<td>-31</td>
<td></td>
</tr>
<tr class="even">
<td>30</td>
<td>-336</td>
<td>-305</td>
<td>-275</td>
<td>-244</td>
<td>-214</td>
<td>-183</td>
<td>-152</td>
<td>-122</td>
<td>-91</td>
<td>-61</td>
<td>-30</td>
<td></td>
</tr>
<tr class="odd">
<td>31</td>
<td>-335</td>
<td></td>
<td>-274</td>
<td></td>
<td>-213</td>
<td>-182</td>
<td></td>
<td>-121</td>
<td></td>
<td>-60</td>
<td>-29</td>
<td></td>
</tr>
</tbody>
</table>
</div>
<div id="tbl-leap" class="anchored">
<table class="table">
<caption>Table&nbsp;12: Gregorian calendar date to negative <code>doty</code> leap year conversion</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Day</th>
<th>Mar</th>
<th>Apr</th>
<th>May</th>
<th>Jun</th>
<th>Jul</th>
<th>Aug</th>
<th>Sep</th>
<th>Oct</th>
<th>Nov</th>
<th>Dec</th>
<th>Jan</th>
<th>Feb</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>-366</td>
<td>-335</td>
<td>-305</td>
<td>-274</td>
<td>-244</td>
<td>-213</td>
<td>-182</td>
<td>-152</td>
<td>-122</td>
<td>-91</td>
<td>-60</td>
<td>-29</td>
</tr>
<tr class="even">
<td>2</td>
<td>-365</td>
<td>-334</td>
<td>-304</td>
<td>-273</td>
<td>-243</td>
<td>-212</td>
<td>-181</td>
<td>-151</td>
<td>-121</td>
<td>-90</td>
<td>-59</td>
<td>-28</td>
</tr>
<tr class="odd">
<td>3</td>
<td>-364</td>
<td>-333</td>
<td>-303</td>
<td>-272</td>
<td>-242</td>
<td>-211</td>
<td>-180</td>
<td>-150</td>
<td>-120</td>
<td>-89</td>
<td>-58</td>
<td>-27</td>
</tr>
<tr class="even">
<td>4</td>
<td>-363</td>
<td>-332</td>
<td>-302</td>
<td>-271</td>
<td>-241</td>
<td>-210</td>
<td>-179</td>
<td>-149</td>
<td>-119</td>
<td>-88</td>
<td>-57</td>
<td>-26</td>
</tr>
<tr class="odd">
<td>5</td>
<td>-362</td>
<td>-331</td>
<td>-301</td>
<td>-270</td>
<td>-240</td>
<td>-209</td>
<td>-178</td>
<td>-148</td>
<td>-118</td>
<td>-87</td>
<td>-56</td>
<td>-25</td>
</tr>
<tr class="even">
<td>6</td>
<td>-361</td>
<td>-330</td>
<td>-300</td>
<td>-269</td>
<td>-239</td>
<td>-208</td>
<td>-177</td>
<td>-147</td>
<td>-117</td>
<td>-86</td>
<td>-55</td>
<td>-24</td>
</tr>
<tr class="odd">
<td>7</td>
<td>-360</td>
<td>-329</td>
<td>-299</td>
<td>-268</td>
<td>-238</td>
<td>-207</td>
<td>-176</td>
<td>-146</td>
<td>-116</td>
<td>-85</td>
<td>-54</td>
<td>-23</td>
</tr>
<tr class="even">
<td>8</td>
<td>-359</td>
<td>-328</td>
<td>-298</td>
<td>-267</td>
<td>-237</td>
<td>-206</td>
<td>-175</td>
<td>-145</td>
<td>-115</td>
<td>-84</td>
<td>-53</td>
<td>-22</td>
</tr>
<tr class="odd">
<td>9</td>
<td>-358</td>
<td>-327</td>
<td>-297</td>
<td>-266</td>
<td>-236</td>
<td>-205</td>
<td>-174</td>
<td>-144</td>
<td>-114</td>
<td>-83</td>
<td>-52</td>
<td>-21</td>
</tr>
<tr class="even">
<td>10</td>
<td>-357</td>
<td>-326</td>
<td>-296</td>
<td>-265</td>
<td>-235</td>
<td>-204</td>
<td>-173</td>
<td>-143</td>
<td>-113</td>
<td>-82</td>
<td>-51</td>
<td>-20</td>
</tr>
<tr class="odd">
<td>11</td>
<td>-356</td>
<td>-325</td>
<td>-295</td>
<td>-264</td>
<td>-234</td>
<td>-203</td>
<td>-172</td>
<td>-142</td>
<td>-112</td>
<td>-81</td>
<td>-50</td>
<td>-19</td>
</tr>
<tr class="even">
<td>12</td>
<td>-355</td>
<td>-324</td>
<td>-294</td>
<td>-263</td>
<td>-233</td>
<td>-202</td>
<td>-171</td>
<td>-141</td>
<td>-111</td>
<td>-80</td>
<td>-49</td>
<td>-18</td>
</tr>
<tr class="odd">
<td>13</td>
<td>-354</td>
<td>-323</td>
<td>-293</td>
<td>-262</td>
<td>-232</td>
<td>-201</td>
<td>-170</td>
<td>-140</td>
<td>-110</td>
<td>-79</td>
<td>-48</td>
<td>-17</td>
</tr>
<tr class="even">
<td>14</td>
<td>-353</td>
<td>-322</td>
<td>-292</td>
<td>-261</td>
<td>-231</td>
<td>-200</td>
<td>-169</td>
<td>-139</td>
<td>-109</td>
<td>-78</td>
<td>-47</td>
<td>-16</td>
</tr>
<tr class="odd">
<td>15</td>
<td>-352</td>
<td>-321</td>
<td>-291</td>
<td>-260</td>
<td>-230</td>
<td>-199</td>
<td>-168</td>
<td>-138</td>
<td>-108</td>
<td>-77</td>
<td>-46</td>
<td>-15</td>
</tr>
<tr class="even">
<td>16</td>
<td>-351</td>
<td>-320</td>
<td>-290</td>
<td>-259</td>
<td>-229</td>
<td>-198</td>
<td>-167</td>
<td>-137</td>
<td>-107</td>
<td>-76</td>
<td>-45</td>
<td>-14</td>
</tr>
<tr class="odd">
<td>17</td>
<td>-350</td>
<td>-319</td>
<td>-289</td>
<td>-258</td>
<td>-228</td>
<td>-197</td>
<td>-166</td>
<td>-136</td>
<td>-106</td>
<td>-75</td>
<td>-44</td>
<td>-13</td>
</tr>
<tr class="even">
<td>18</td>
<td>-349</td>
<td>-318</td>
<td>-288</td>
<td>-257</td>
<td>-227</td>
<td>-196</td>
<td>-165</td>
<td>-135</td>
<td>-105</td>
<td>-74</td>
<td>-43</td>
<td>-12</td>
</tr>
<tr class="odd">
<td>19</td>
<td>-348</td>
<td>-317</td>
<td>-287</td>
<td>-256</td>
<td>-226</td>
<td>-195</td>
<td>-164</td>
<td>-134</td>
<td>-104</td>
<td>-73</td>
<td>-42</td>
<td>-11</td>
</tr>
<tr class="even">
<td>20</td>
<td>-347</td>
<td>-316</td>
<td>-286</td>
<td>-255</td>
<td>-225</td>
<td>-194</td>
<td>-163</td>
<td>-133</td>
<td>-103</td>
<td>-72</td>
<td>-41</td>
<td>-10</td>
</tr>
<tr class="odd">
<td>21</td>
<td>-346</td>
<td>-315</td>
<td>-285</td>
<td>-254</td>
<td>-224</td>
<td>-193</td>
<td>-162</td>
<td>-132</td>
<td>-102</td>
<td>-71</td>
<td>-40</td>
<td>-9</td>
</tr>
<tr class="even">
<td>22</td>
<td>-345</td>
<td>-314</td>
<td>-284</td>
<td>-253</td>
<td>-223</td>
<td>-192</td>
<td>-161</td>
<td>-131</td>
<td>-101</td>
<td>-70</td>
<td>-39</td>
<td>-8</td>
</tr>
<tr class="odd">
<td>23</td>
<td>-344</td>
<td>-313</td>
<td>-283</td>
<td>-252</td>
<td>-222</td>
<td>-191</td>
<td>-160</td>
<td>-130</td>
<td>-100</td>
<td>-69</td>
<td>-38</td>
<td>-7</td>
</tr>
<tr class="even">
<td>24</td>
<td>-343</td>
<td>-312</td>
<td>-282</td>
<td>-251</td>
<td>-221</td>
<td>-190</td>
<td>-159</td>
<td>-129</td>
<td>-99</td>
<td>-68</td>
<td>-37</td>
<td>-6</td>
</tr>
<tr class="odd">
<td>25</td>
<td>-342</td>
<td>-311</td>
<td>-281</td>
<td>-250</td>
<td>-220</td>
<td>-189</td>
<td>-158</td>
<td>-128</td>
<td>-98</td>
<td>-67</td>
<td>-36</td>
<td>-5</td>
</tr>
<tr class="even">
<td>26</td>
<td>-341</td>
<td>-310</td>
<td>-280</td>
<td>-249</td>
<td>-219</td>
<td>-188</td>
<td>-157</td>
<td>-127</td>
<td>-97</td>
<td>-66</td>
<td>-35</td>
<td>-4</td>
</tr>
<tr class="odd">
<td>27</td>
<td>-340</td>
<td>-309</td>
<td>-279</td>
<td>-248</td>
<td>-218</td>
<td>-187</td>
<td>-156</td>
<td>-126</td>
<td>-96</td>
<td>-65</td>
<td>-34</td>
<td>-3</td>
</tr>
<tr class="even">
<td>28</td>
<td>-339</td>
<td>-308</td>
<td>-278</td>
<td>-247</td>
<td>-217</td>
<td>-186</td>
<td>-155</td>
<td>-125</td>
<td>-95</td>
<td>-64</td>
<td>-33</td>
<td>-2</td>
</tr>
<tr class="odd">
<td>29</td>
<td>-338</td>
<td>-307</td>
<td>-277</td>
<td>-246</td>
<td>-216</td>
<td>-185</td>
<td>-154</td>
<td>-124</td>
<td>-94</td>
<td>-63</td>
<td>-32</td>
<td>-1</td>
</tr>
<tr class="even">
<td>30</td>
<td>-337</td>
<td>-306</td>
<td>-276</td>
<td>-245</td>
<td>-215</td>
<td>-184</td>
<td>-153</td>
<td>-123</td>
<td>-93</td>
<td>-62</td>
<td>-31</td>
<td></td>
</tr>
<tr class="odd">
<td>31</td>
<td>-336</td>
<td></td>
<td>-275</td>
<td></td>
<td>-214</td>
<td>-183</td>
<td></td>
<td></td>
<td>-92</td>
<td>-61</td>
<td>-30</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
</section>
<section id="sec-subyear" class="level3">
<h3 class="anchored" data-anchor-id="sec-subyear">Subyear units</h3>
<p>In addition to serving as a part of the Gregorian date coordinate system described above, months can also indicate the current season or quarter. <code>Deks</code> can also serve as indicator of subyear units like seasons.</p>
<section id="sec-seasons" class="level4">
<h4 class="anchored" data-anchor-id="sec-seasons">Seasons</h4>
<p>We can use the tables above to convert any Gregorian calendar date to a <code>doty</code> number. This is especially useful for variable dates that have to be converted every year. For example, the dates of the solstices, the longest and shortest days of the year, vary slightly every year. Instead of calculating the exact <code>doty</code> number of the solstices ourselves we could translate from existing Gregorian calendar dates. Solstices and equinoxes (the points in between the solstices) are the basis of the some holidays, such as <a href="https://en.wikipedia.org/wiki/Nowruz">Nowruz</a>.</p>
<p>The dates of the solstices and the equinoxes can be used as definitions of the seasons. Each season has its opposite. The opposite of Spring is Fall and the opposite of Summer is Winter. These opposites are always occurring simultaneously, one opposing season in the Northern hemisphere and the other in the Southern hemisphere. The table below lists the opposing seasons in the North and South columns (which correspond to the Northern and Southern hemispheres) and the approximate dates of the solstices and the equinoxes that mark the start of each season.</p>
<div id="tbl-soleq" class="anchored">
<table class="table">
<caption>Table&nbsp;13: Solstice and equinox Gregorian calendar and <code>doty</code> dates</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 21%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>North</th>
<th>South</th>
<th><code>doty</code></th>
<th><code>dotm</code></th>
<th>Date</th>
<th>Event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S0</td>
<td>Spring</td>
<td>Fall</td>
<td>19</td>
<td>0+19</td>
<td>March 20</td>
<td>Northward Equinox</td>
</tr>
<tr class="even">
<td>S1</td>
<td>Summer</td>
<td>Winter</td>
<td>111</td>
<td>3+19</td>
<td>June 20</td>
<td>Northward Solstice</td>
</tr>
<tr class="odd">
<td>S2</td>
<td>Fall</td>
<td>Spring</td>
<td>205</td>
<td>6+21</td>
<td>September 22</td>
<td>Southward Equinox</td>
</tr>
<tr class="even">
<td>S3</td>
<td>Winter</td>
<td>Summer</td>
<td>295</td>
<td>9+20</td>
<td>December 21</td>
<td>Southward Solstice</td>
</tr>
</tbody>
</table>
</div>
<p>Using the information in the table above, we can group the <code>deks</code> and <code>pents</code> in a year according to the seasons in which they occur. We identify <code>deks</code> using the first 2 digits of the 3-digit day number of any day in that <code>dek</code>. The <code>pent</code> number is twice the <code>dek</code> number plus one if the <code>dotd</code> is greater than 4 (<span class="math inline">\(dek \cdot 2 + dotd &gt; 4\)</span>). For example, <code>Day 19</code> is the last day in <code>Dek 1</code> and <code>Pent 3</code>, while <code>Day 111</code> is the second day in <code>Dek 11</code> and <code>Pent 22</code>.</p>
<p>We can round up the start of the first season and round down the start of the second season to obtain the division of <code>pents</code> by season as summarized in the table below. It is important to note that the last season starts in <code>Pent 59</code> of one year and ends with <code>Pent 3</code> of the subsequent year. In common years, each season in the table above has 18 <code>pents</code> (90 days), except for the season in the second row, which has 19 <code>pents</code> (95 days). In leap years, the season in the last row has 18.2 pents (91 days).</p>
<div id="tbl-seasons" class="anchored">
<table class="table">
<caption>Table&nbsp;14: The <code>pents</code> that begin and end each season</caption>
<thead>
<tr class="header">
<th>Code</th>
<th>North</th>
<th>South</th>
<th>First</th>
<th>Last</th>
<th>Duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S0</td>
<td>Spring</td>
<td>Fall</td>
<td>4</td>
<td>21</td>
<td>18</td>
</tr>
<tr class="even">
<td>S1</td>
<td>Summer</td>
<td>Winter</td>
<td>22</td>
<td>40</td>
<td>19</td>
</tr>
<tr class="odd">
<td>S2</td>
<td>Fall</td>
<td>Spring</td>
<td>41</td>
<td>58</td>
<td>18</td>
</tr>
<tr class="even">
<td>S3</td>
<td>Winter</td>
<td>Summer</td>
<td>59</td>
<td>3</td>
<td>18</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-qdew" class="level4">
<h4 class="anchored" data-anchor-id="sec-qdew"><code>Qops</code>, <code>Delts</code>, <code>Eps</code> and <code>Waus</code></h4>
<section id="sec-q" class="level5">
<h5 class="anchored" data-anchor-id="sec-q"><code>Qops</code></h5>
<p>In contrast to the variable length of seasons, other <code>Decalendar</code> units are constant length. Of these constant length units, <code>qops</code> (<code>qoppas</code>, <code>ϟ</code>) are most like seasons. <code>Qops</code> divide the year into four parts, but unlike seasons, <code>qops</code> do not include <code>Pent 72</code>, the last <code>pent</code> of the year. <code>Pent 72</code> is not included in the last <code>qop</code> so that each <code>qop</code> is 9 <code>deks</code> and 90 days long. The omission of <code>Dek 36</code> also maintains the pattern of alternating even and odd numbers in each row. This omission leaves out only 5 or 6 days per year, because <code>Dek 36</code> overlaps with <code>Dek 0</code>. The table below shows the division of <code>deks</code> by <code>qop</code>.</p>
<div id="tbl-q" class="anchored">
<table class="table">
<caption>Table&nbsp;15: The <code>deks</code> that begin and end each <code>qop</code></caption>
<thead>
<tr class="header">
<th>Code</th>
<th>First</th>
<th>Last</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Q0</td>
<td>0</td>
<td>8</td>
</tr>
<tr class="even">
<td>Q1</td>
<td>9</td>
<td>17</td>
</tr>
<tr class="odd">
<td>Q2</td>
<td>18</td>
<td>26</td>
</tr>
<tr class="even">
<td>Q3</td>
<td>27</td>
<td>35</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-d" class="level5">
<h5 class="anchored" data-anchor-id="sec-d"><code>Delts</code></h5>
<p>In addition to <code>qops</code> shown above, <code>Decalendar</code> describes 3 other similar units called <code>delts</code> (<code>deltas</code>, <code>δ</code>), <code>eps</code> (<code>epsilons</code>, <code>ε</code>), and <code>waus</code> (<code>ϛ</code>). These units do not leave out as many days in each year, because they split the year by day, rather than by <code>dek</code>. <code>Delts</code>, <code>eps</code>, and <code>wau</code> split the year into 4, 5, and 6 parts, respectively. <code>Delts</code> are 91 days long and leave out one day at the end of common years and two days at the end of leap years. Just as above, leaving out a small number of days at the end of the year preserves a pattern that can be useful for remembering the days on which <code>delts</code> start and end. In the table above, not only do rows alternate between even and odd numbers, but the <code>delt</code> number is the last digit of both the start and the end day of the <code>delt</code>. The table below list the numbers of the days that begin and end each <code>delt</code>.</p>
<div id="tbl-d" class="anchored">
<table class="table">
<caption>Table&nbsp;16: The days that begin and end each <code>delt</code></caption>
<thead>
<tr class="header">
<th>Code</th>
<th>First</th>
<th>Last</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>D0</td>
<td>0</td>
<td>90</td>
</tr>
<tr class="even">
<td>D1</td>
<td>91</td>
<td>181</td>
</tr>
<tr class="odd">
<td>D2</td>
<td>182</td>
<td>272</td>
</tr>
<tr class="even">
<td>D3</td>
<td>273</td>
<td>363</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-e" class="level5">
<h5 class="anchored" data-anchor-id="sec-e"><code>Eps</code></h5>
<p>Unlike <code>delts</code>, <code>eps</code> are 73 days long and do not leave out any days from common years. <code>Qops</code>, <code>delts</code>, and <code>eps</code> all leave out leap days in leap years. The table below list the numbers of the days that begin and end each <code>ep</code>.</p>
<div id="tbl-e" class="anchored">
<table class="table">
<caption>Table&nbsp;17: The days that begin and end each <code>ep</code></caption>
<thead>
<tr class="header">
<th>Code</th>
<th>First</th>
<th>Last</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E0</td>
<td>0</td>
<td>72</td>
</tr>
<tr class="even">
<td>E1</td>
<td>73</td>
<td>145</td>
</tr>
<tr class="odd">
<td>E2</td>
<td>146</td>
<td>218</td>
</tr>
<tr class="even">
<td>E3</td>
<td>219</td>
<td>291</td>
</tr>
<tr class="odd">
<td>E4</td>
<td>292</td>
<td>364</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-w" class="level5">
<h5 class="anchored" data-anchor-id="sec-w"><code>Waus</code></h5>
<p>The only unit that can include the leap year is a <code>wau</code> (<code>ϛ</code>), which is 61 days long and follows a similar pattern as a <code>delt</code>, except the last <code>wau</code> in common years is 1 day short than all the others. The table below list the numbers of the days that begin and end each <code>wau</code>. As with <code>delts</code>, the <code>wau</code> number is the last digit of the numbers of its first and last day.</p>
<div id="tbl-z" class="anchored">
<table class="table">
<caption>Table&nbsp;18: The days that begin and end each <code>wau</code></caption>
<thead>
<tr class="header">
<th>Code</th>
<th>First</th>
<th>Last</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>W0</td>
<td>0</td>
<td>60</td>
</tr>
<tr class="even">
<td>W1</td>
<td>61</td>
<td>121</td>
</tr>
<tr class="odd">
<td>W2</td>
<td>122</td>
<td>182</td>
</tr>
<tr class="even">
<td>W3</td>
<td>183</td>
<td>243</td>
</tr>
<tr class="odd">
<td>W4</td>
<td>244</td>
<td>304</td>
</tr>
<tr class="even">
<td>W5</td>
<td>305</td>
<td>365</td>
</tr>
</tbody>
</table>
</div>
<p>All of the subyear unit codes can be preceded by a year and followed by a day number. The midpoint of common years is noon on the first day of <code>Delt 2</code>, <code>D2+00.5</code> or <code>+182.5</code>, and the midpoint of leap years is midnight of the first day of <code>Wau 3</code>, <code>W3+00.0</code> or <code>+183.0</code>. The first day of Spring in northern hemisphere and Fall in the southern hemisphere in the year 2000 is <code>2000S0+00</code> or <code>2000+020</code>, while the last day of this season is <code>2000S0+89</code> or <code>2000+109</code>. The subyear units are essentially date intervals, series of contiguous dates. <code>Decalendar</code> includes very powerful approaches to describing series of dates, times, and <code>stamps</code>.</p>
</section>
</section>
</section>
</section>
<section id="sec-series" class="level2">
<h2 class="anchored" data-anchor-id="sec-series">Series</h2>
<p>A single <code>doty</code> number, such as <code>Day 0</code>, implies a duration on 1 day. We can indicate a duration of multiple days by listing consecutive days in a <code>series</code>. A <code>series</code> consists of dates, times, or <code>stamps</code> separated by commas (<code>,</code>). The items in a <code>series</code> should all be of the same type. In other words, <code>series</code> should be homogeneous and not mix dates, times, and <code>stamps</code>. The first 3 days of the year in the form of a <code>series</code> would be written <code>0,1,2</code>, while the last three days would be <code>-3,-2,-1</code>. The first half a day, from midnight to noon, could be written <code>0,.1,.2,.3,.4</code>.</p>
<section id="sec-slices" class="level3">
<h3 class="anchored" data-anchor-id="sec-slices">Slices</h3>
<p>Instead of listing every single day in a <code>series</code>, we can “slice” from <code>Day 0</code> up to but not including <code>Day 3</code> by writing <code>:3</code>. <code>Simple slices</code> consist of a <code>start</code> and a <code>stop</code> separated by a colon (<code>start:stop</code>). When the <code>start</code> is omitted, <code>slices</code> begin at the first value, which in the context of a year is <code>Day 0</code> and in the context of a day is midnight. Therefore, writing <code>:3</code> is the same as writing <code>0:3</code>, both represent the first 3 days of the year: <code>0,1,2</code>. Using this approach, we can shorten the series <code>0,.1,.2,.3,.4</code> to <code>:.5</code>. If we omit the <code>stop</code>, instead of the <code>start</code>, we would “slice” up to and including the last value.</p>
<p>In the context of <code>doty</code> dates, omitting the <code>stop</code> value obtains all of the days in the year after the <code>start</code>, because the default <code>stop</code> is the number of days in the year (<code>n</code>). For example, the <code>slice</code> <code>3:</code> has a <code>start</code> of <code>Day 3</code> and a <code>stop</code> of <code>n</code>, and thus represents every day in the year except the first 3. The number of items we obtain from a <code>slice</code> is called a <code>span</code>. To calculate the <code>span</code>, we subtract the <code>start</code> from the <code>stop</code> (<span class="math inline">\(stop-start\)</span>). In a common year, the <code>span</code> of <code>003:</code> is <span class="math inline">\(n-3=362\)</span>, while in a leap year it would be <span class="math inline">\(n-3=363\)</span>. If both the <code>start</code> and the <code>stop</code> are omitted, every day is included (<span class="math inline">\(span=n-0\)</span>). The tables below lists the seasons, <code>qops</code>, and <code>delts</code> in the form of <code>slices</code>.</p>
<div id="tbl-fourpart" class="anchored">
<table class="table">
<caption>Table&nbsp;19: The slices that represent the 4-part subyear units</caption>
<thead>
<tr class="header">
<th>Index</th>
<th>Season</th>
<th>Qop</th>
<th>Delt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>78:170</td>
<td>:90</td>
<td>:91</td>
</tr>
<tr class="even">
<td>1</td>
<td>170:264</td>
<td>90:180</td>
<td>91:182</td>
</tr>
<tr class="odd">
<td>2</td>
<td>264:354</td>
<td>180:270</td>
<td>182:273</td>
</tr>
<tr class="even">
<td>3</td>
<td>354:78</td>
<td>270:360</td>
<td>273:364</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-steps" class="level3">
<h3 class="anchored" data-anchor-id="sec-steps">Steps</h3>
<p>The <code>simple slices</code> (<code>start:stop</code>) described above are a type of time <code>segment</code>, an unbroken time interval. To break up a <code>simple slice</code> into a non-consecutive <code>series</code>, we can add a <code>step</code> value and create a <code>stepped slice</code> (<code>start:stop:step</code>). <code>Stepped slices</code> move in <code>step</code>-sized “steps” starting from <code>start</code>, skipping over <span class="math inline">\(step-1\)</span> items with each “step”, keeping only items that are “stepped” on.</p>
<p>In other words, <code>stepped slices</code> keep items whose index (zero-based position) in the <code>slice</code> is evenly divisible by <code>step</code>. A <code>step</code> value of 1 keeps every item, because every index is divisible by 1, and a <code>step</code> of 2 keeps every other item, those with even-numbered indexes. <code>Day 0</code> and every other third day in the year thereafter (<code>Day 3</code>, <code>Day 6</code>, etc.) can be represented by the <code>slice</code> <code>::3</code>.</p>
<p>To create a <code>series</code> of times on days throughout the year, we can use a <code>slice</code> with a <code>series</code> of <code>steps</code>. The <code>slice</code> <code>:365:1,1,3</code> represents all of the <code>Decalendar</code> workdays in a year. It is necessary to specify 365 as the <code>stop</code>, so that Leap Day (<code>Day 365</code>) is not included as a workday in leap years. Similarly, <code>3::1,4</code> is a <code>seq</code> that represents all of the regular restdays, not including the Leap Day holiday.</p>
<p><code>Stepped slices</code> cannot be included in <code>series</code>, because both use commas (<code>,</code>) and it would not possible to differentiate a <code>series</code> of <code>steps</code> from subsequent items in the <code>series</code>. The simple rule is that <code>slices</code> with more than 1 colon (<code>:</code>) cannot be part of a series. For example, <code>:365:1,1,3</code> is a <code>stepped slice</code> with a <code>series</code> of 3 <code>steps</code> rather than a series consisting of a <code>slice</code> and two numbers.</p>
</section>
<section id="sec-spreads" class="level3">
<h3 class="anchored" data-anchor-id="sec-spreads">Spreads</h3>
<p>To create <code>series</code> of consecutive items with breaks in between, it may be better to use a <code>spread</code> than a <code>slice</code>. <code>Simple spreads</code> consist of either a <code>start</code> and a <code>span</code> (<code>start&gt;span</code>) separated by a greater-than sign (<code>&gt;</code>) or a <code>stop</code> and a <code>span</code> (<code>stop&lt;span</code>) separated by a less-than (<code>&lt;</code>) sign. The default <code>start</code> and <code>stop</code> values are the same for both <code>slices</code> and <code>spreads</code>. We can <code>spread</code> forward from the default <code>start</code> to capture the first <code>span</code> days in a year. For example, the first 3 days in a year can be represented by the <code>spread</code> <code>&gt;3</code>, which is synonymous with the <code>slice</code> <code>:3</code>. In this example, the <code>start</code> is 0, while the <code>stop</code> and the <code>span</code> are both 3. In addition to default <code>start</code> and <code>stop</code> values, <code>spreads</code> also have default <code>span</code> values. A <code>spread</code> that only uses default values (<code>&gt;</code> or <code>&lt;</code>) will include every day in the year (<span class="math inline">\(span=n\)</span>).</p>
<p>If we “spread” forward from a positive <code>start</code>, the default <code>span</code> is <span class="math inline">\(n-start\)</span>. If we spread backward from a positive <code>stop</code>, the default <code>span</code> is <code>stop</code>. We can <code>spread</code> backward from the default <code>stop</code> to capture the last <code>span</code> days in a year. For example, <code>&lt;3</code> represents the last 3 days of any year. We could also use a negative <code>start</code> of <code>-3</code>, the third to last day of any year, to create the <code>slice</code> <code>-3:</code> and the <code>spread</code> <code>-3&gt;</code>, both of which are synonymous with <code>&lt;3</code>. One advantage of <code>spreads</code> over <code>slices</code> is the ability to access days from the end of a year without negative numbers. A <code>span</code> value of zero does not return any items. Negative <code>span</code> values reverse the direction of the first sign, turning <code>start</code> into <code>stop</code> and vice versa.</p>
</section>
<section id="sec-splits" class="level3">
<h3 class="anchored" data-anchor-id="sec-splits">Splits</h3>
<p>As with <code>stepped slices</code>, we can create non-consecutive <code>series</code> by “splitting” a <code>simple spread</code> (<code>start&gt;span</code> or <code>stop&lt;span</code>) into <code>split spread</code> (e.g.&nbsp;<code>start&gt;span&gt;split</code>) with a <code>split</code> value that works like the opposite of a <code>step</code>. While <code>steps</code> keep items that are “stepped” on, <code>splits</code> exclude items that are used to create the boundaries of the <code>splits</code>. The default <code>split</code> value is <code>span</code>, meaning that the entire <code>span</code> is included in one <code>split</code>.</p>
<p>A <code>split spread</code> with a <code>split</code> value of 1 (<code>start&gt;span&gt;1</code>) is the same as a <code>stepped slice</code> with a <code>step</code> value of 2 (<code>start:stop:2</code>). <code>Split</code> values greater than 1 but less than <code>span</code> will yield a <code>series</code> of <code>segments</code>. If <code>split</code> is zero (<code>start&gt;span&gt;0</code>), the <code>split spread</code> will not return any items. A negative <code>split</code> value reverses the direction of the second greater-than sign (<code>start&gt;span&gt;-2</code> and <code>start&gt;span&lt;2</code> are synonymous). This can be useful when providing a series of <code>split</code> values. Negative <code>split</code> values reverse the direction of a <code>split</code> and a <code>split</code> value of zero skips a <code>split</code>. Just like <code>stepped slices</code>, <code>split spreads</code> cannot be included in a <code>series</code>, because every <code>split</code> can have a <code>series</code> of values.</p>
<p>The direction of the second sign in <code>split spreads</code> determines whether we begin creating splits from the <code>start</code> (<code>&gt;</code>) or the <code>stop</code> (<code>&lt;</code>) of the <code>span</code>. If the first two values (<code>start</code> and <code>span</code> or <code>stop</code> and <code>span</code>) are blank, the direction of the first sign does not matter and the first two signs can be combined into a “much greater-than sign” (<code>≫</code>), a “much less-than sign” (<code>≪</code>), a diamond (<code>♢</code>), or simply an <code>x</code>. The split spreads <code>≫4</code> and <code>♢4</code> are synonymous; both skip every 5th day to create groups of 4 days throughout the year starting with the first 4 days of the year <code>&gt;4</code>. Notably, <code>≫4</code> and <code>♢4</code> will always end with a <code>segment</code> containing the last 4 days of common years, <code>360:364</code>, <code>360&gt;4</code>, or <code>364&lt;4</code>, even in leap years, because partial <code>splits</code> are not allowed.</p>
</section>
<section id="sec-spaces" class="level3">
<h3 class="anchored" data-anchor-id="sec-spaces">Spaces</h3>
<p>The patterns described above require that <code>splits</code> are separated by the default <code>space</code> value of 1. We can specify a different <code>space</code> value in the form <code>start&gt;span&gt;split&gt;space</code>. The <code>split spreads</code> <code>≫3&gt;2</code> and <code>♢3&gt;2</code> create 3-day <code>splits</code> separated by 2-day <code>spaces</code>. This is the pattern of workdays in the <code>Decalendar</code> system. The first <code>segment</code> of <code>≫3&gt;2</code> and <code>♢3&gt;2</code> can be written as <code>:3</code>, <code>&gt;3</code>, or <code>3&lt;</code>, while the last <code>segment</code> is <code>360:363</code>, <code>360&gt;3</code>, or <code>363&lt;3</code>. The workdays in the first <code>dek</code> of <code>≫3&gt;2</code> and <code>♢3&gt;2</code> can be written as the following <code>series</code> of <code>segments</code>: <code>:4,5:8</code>, <code>&gt;3,5&gt;3</code>, or <code>3&lt;,8&lt;3</code>. Unlike <code>stepped slices</code> and <code>split spreads</code>, <code>simple slices</code> and <code>simple spreads</code> can be used in <code>series</code>.</p>
<p>A <code>space</code> value of 0 may also be useful. For example, <code>delts</code>, <code>qops</code>, <code>eps</code>, and <code>waus</code> can be summarized as <code>split spreads</code> as shown in the table below. When <code>space</code> is zero, the direction of the third sign does not matter. The <code>split spreads</code> <code>≫61&gt;0</code>, <code>♢61&gt;0</code>, <code>≫61&lt;0</code>, and <code>♢61&lt;0</code> all represents the <code>waus</code> in a year. <code>Waus</code> divide leap years evenly and <code>eps</code> divide common years evenly. Therefore, <code>x61&gt;0</code> and <code>x61&lt;0</code> can represent all of the <code>waus</code> in leap years, just like <code>x73&gt;0</code> and <code>x73&lt;0</code> can represent all of the <code>eps</code> in common years.</p>
<div id="tbl-constant" class="anchored">
<table class="table">
<caption>Table&nbsp;20: The spreads that represent the constant length subyear units</caption>
<thead>
<tr class="header">
<th>Unit</th>
<th>Spread</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Delt</td>
<td><code>≫91&gt;0</code></td>
</tr>
<tr class="even">
<td>Qop</td>
<td><code>≫90&gt;0</code></td>
</tr>
<tr class="odd">
<td>Ep</td>
<td><code>≫73&gt;0</code></td>
</tr>
<tr class="even">
<td>Wau</td>
<td><code>≫61&gt;0</code></td>
</tr>
</tbody>
</table>
</div>
<p>If <code>space</code> is greater than zero and the second and third sign are pointing in opposite directions, the resulting time <code>segments</code> will overlap. The <code>split spreads</code> <code>&gt;1&gt;.4&lt;.2</code> and <code>&lt;1&lt;.4&gt;.2</code> both result in the same 4 overlapping time <code>segments</code>: <code>:.4</code>, <code>.2:.6</code>, <code>.4:.8</code>, <code>.6:1</code>. Negative values can be used in a <code>series</code> of <code>spaces</code> to temporarily reverse the direction and intersperse overlapping and non-overlapping <code>segments</code>. The <code>split spread</code> <code>&gt;1&gt;.4&lt;.2,-.1</code> yields two <code>segments</code> that overlap and one <code>segment</code> that does not overlap: <code>:.4</code>, <code>.2:.6</code>, <code>.6:1</code>.</p>
<p>Overlapping segments could be used to plan work shifts that require a hand-off between teams. The segments created by <code>&gt;1&gt;.4&lt;.2</code> are shifted by two <code>dimes</code> in relation to each other and overlap by 2 <code>dimes</code>. If these segments are in <code>Zone 0</code> time, they represent the normal workday (<code>.3:.7</code>) for <code>Zone 3</code> (<code>:.4</code>), <code>Zone 1</code>(<code>.2:.6</code>), <code>Zone -1</code>(<code>.4:.8</code>), and <code>Zone -3</code>(<code>.6:1</code>). Each of these 4 segments could represent a team working during the normal workday in their respective time zone. All but the last team would have two dimes of overlap with the subsequent team.</p>
</section>
<section id="sec-seq" class="level3">
<h3 class="anchored" data-anchor-id="sec-seq">Sequential spreads and slices</h3>
<p><code>Split spreads</code> can be combined with other <code>spreads</code> into <code>sequences</code> called <code>seq spreads</code> (<code>sequential spreads</code>). The intuition behind <code>seq spreads</code> and is that each item in the first (outer) <code>spread</code> serves as a starting point for the second (inner) <code>spread</code>. The main use of <code>seq spreads</code> is to first “spread” across days and then “spread” across times in those days. We can combine <code>≫3&gt;2</code>, a <code>split spread</code> that represents the <code>Decalendar</code> workdays, with <code>.3&gt;.4</code>, a <code>simple spread</code> that provides the <code>start</code> and <code>span</code> of the <code>Decalendar</code> workday, to obtain <code>≫3&gt;2&gt;.3&gt;.4</code>, a <code>seq spread</code> that represents the time spent at work in a <code>Decalendar</code> year.</p>
<p>In this <code>seq spread</code>, the <code>split</code> is the number of workdays (<code>3</code>), the space is the number of restdays (<code>2</code>), the second-to-last number is the <code>start</code> of the workday (<code>.3</code>) and the last number is the workday <code>span</code> (<code>.4</code>). The <code>spread</code> <code>≫3&gt;2&gt;.3&gt;.4</code> first starts at midnight of each workday, then moves forward 3 <code>dimes</code> to the new <code>start</code> of <code>Dot 3</code>, and then “spreads” forward by a <code>span</code> of 4 <code>dimes</code> to the new <code>stop</code> of <code>Dot 7</code>. We could replace the start of the workday in <code>≫3&gt;2&gt;.3&gt;.4</code> with the end of workday if we reverse the last sign: <code>≫3&gt;2&gt;.7&lt;.4</code>, because <code>.3&gt;.4</code> and <code>.7&lt;.4</code> are synonymous.</p>
<p>We combine the two <code>spreads</code> with <code>&gt;</code> because we want to move forward from the beginning of each workday, instead of backward to the previous day. If we combined <code>≫3&gt;2</code> and <code>.3&gt;.4</code> with <code>&lt;</code>, the resulting <code>spread</code> <code>≫3&gt;2&lt;.3&gt;.4</code> would move backward from midnight of each workday to <code>Dot 7</code> of each previous day and then “spread” forward to <code>Dot 1</code> of each workday. We may want to use such a mixed direction <code>seq spreads</code> when dealing with time zones. If we lived in <code>Zone -3</code> and wanted to know how the workdays in <code>Zone 4</code> translated into our time zone, we could take the <code>spread</code> <code>≫3&gt;2&gt;.3&gt;.4</code> and move its <code>start</code> to 7 <code>dimes</code> earlier: <code>≫3&gt;2&lt;.4&gt;.4</code>. <code>Seq spreads</code> enable such time zone conversions without the use of negative numbers.</p>
<p>The <code>seq slice</code> equivalent of <code>≫3&gt;2&gt;.3&gt;.4</code> is <code>:365:1,1,3:.3:.7</code>. <code>Seq spreads</code> will always be a more succinct way for creating long consecutive sequences with breaks than <code>slices</code>. For example, to include a lunch break in the middle of work, we could simply add a <code>split</code> and a <code>space</code> to the <code>seq spread</code> above: <code>≫3&gt;2&gt;.3&gt;.4&gt;.18&gt;.04</code>. To do the same with a <code>seq slice</code>, we have to create 17 steps of 0.01 and a step of .04: <code>:365:1,1,3:.3:.7:17*1%,4%</code>. Here, we are using the replication operator (<code>*</code>) to avoid writing 0.01 17 times and the percent operator (<code>%</code>) to save a few characters, but even so the <code>seq slice</code> is not as concise as the <code>seq spread</code>. The table below shows each part of this schedule in the form of <code>simple slices</code> and <code>simple spreads</code>.</p>
<div id="tbl-workday" class="anchored">
<table class="table">
<caption>Table&nbsp;21: A workday schedule with a lunch break</caption>
<thead>
<tr class="header">
<th>slice</th>
<th>spread</th>
<th>spread</th>
<th>label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.30:.48</td>
<td>.30&gt;.18</td>
<td>.48&lt;.18</td>
<td>work0</td>
</tr>
<tr class="even">
<td>.48:.52</td>
<td>.48&gt;.04</td>
<td>.52&lt;.04</td>
<td>lunch</td>
</tr>
<tr class="odd">
<td>.52:.70</td>
<td>.52&gt;.18</td>
<td>.70&lt;.18</td>
<td>work1</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-pom" class="level3">
<h3 class="anchored" data-anchor-id="sec-pom">Pomodoro</h3>
<p>Another real-life application of <code>spreads</code> can be to intersperse breaks in between periods of work as in the <a href="https://en.wikipedia.org/wiki/Pomodoro_Technique">Pomodoro technique</a>. The times spent working and resting can vary, but a reasonable translation of the original Pomodoro into the <code>Declock</code> units would be to have each <code>pomodoro</code> consist of 17 <code>mils</code> of work and 3 <code>mils</code> of rest, with a 17 <code>mil</code> break after every 4 <code>pomodoros</code>. To repeat 16 <code>pomodoros</code> throughout the <code>Decalendar</code> workday, we could use the following <code>seq spread</code>: <code>.3&gt;.7&gt;.08&gt;.02⋙.017&gt;.003</code>. Here, we use the “very much greater-then sign” (<code>⋙</code>) instead of a combination of a “much greater-than sign” (<code>≫</code>) and a greater-than sign (<code>&gt;</code>). The <code>pomodoro</code> pattern is difficult to capture with a <code>slice</code> because we have to use <code>*</code> for the steps of the inner and the outer <code>slice</code>: <code>.3:.7:8*.01,.02:::17*.001,.003</code>.</p>
<section id="sec-rep" class="level4">
<h4 class="anchored" data-anchor-id="sec-rep">Replication operator</h4>
<p>The replication operator (<code>*</code>) is very useful for replacing repetitive values. For example, to divide any year into six parts we could use the <code>spread</code> <code>≫5*61,60⁺&gt;0</code> to create 5 “splits” that are all 61 days long and one last “split” that is <code>60⁺</code> days (60 days in a common year or 61 days in a leap year) long. The <code>*</code> helps us avoid the repetitiveness of writing <code>≫61,61,61,61,61,60⁺&gt;0</code>. In addition to being used in the <code>split</code> and <code>space</code> of a <code>split spread</code> or the <code>step</code> of a <code>stepped slice</code>, the <code>*</code> can also be used in the <code>span</code> of a <code>split spread</code> or the <code>stop</code> of a <code>stepped slice</code> to indicate has many cycles of <code>splits</code> or <code>steps</code> we want to complete. For example, <code>&gt;4*&gt;5*61,60⁺&gt;0</code> indicates that we want 4 years (the current year and the 3 subsequent years) “split” into 6 parts for a total of 24 parts. In other words, <code>4*</code> means that we want to stop cycling after completing four yearly cycles. We can read <code>4*</code> out loud as “four times” because it means we intend to go through the yearly cycle “four times”.</p>
</section>
<section id="sec-per" class="level4">
<h4 class="anchored" data-anchor-id="sec-per">Percent, permil, and permyr operators</h4>
<p>We can make the <code>seq spread</code> above even shorter by using the <code>per</code> operators: <code>%</code>, <code>‰</code>, and <code>‱</code>. Most of the values in <code>.3&gt;2*&gt;.08&gt;.02⋙.017&gt;.003</code> are either percents (.01 or ¹/₁₀₀) or permils (.001 or ¹/₁₀₀₀) of a day, we can therefore rewrite this <code>seq spread</code> as <code>.3&gt;2*&gt;8%&gt;2%⋙17‰&gt;3‰</code>. It may be difficult to write the permil (<code>‰</code>) operator (hex: <code>2030</code>, html: <code>&amp;permil;</code>, vim: <code>%0</code>, compose: <code>%o</code>), because it does not appear on a typical keyboard, so it is also possible to write <code>.3&gt;2*&gt;8%&gt;2%⋙17‰&gt;3‰</code> as <code>.3&gt;2*&gt;8%&gt;2%⋙17m&gt;3m</code>, with the letter <code>m</code>, which stands for <code>mil</code>, replacing <code>‰</code>. In addition to the percent (<code>%</code>) and permil (<code>‰</code>) operators, there is also the permyr (<code>‱</code>) operator, which is short for permyriad and represents <code>Declock phrases</code> (10⁻⁴).</p>
</section>
<section id="sec-3s" class="level4">
<h4 class="anchored" data-anchor-id="sec-3s">Pently schedules as seq spreads, splices, and sleds</h4>
<p>We can use <code>seq spreads</code> to describe the <a href="#sched"><code>pently</code>schedules</a>. <code>Schedule 5</code> is particularly interesting because it includes all of the days of the year. <code>Spreads</code> that include every item can be written as <code>&gt;</code> or <code>&lt;</code>, but <code>seq spreads</code> must have at least 5 values. The <code>Schedule 5</code> <code>seq spread</code> <code>≫≫.38&gt;.24</code> has 4 blank values, which represent the default <code>start</code>, <code>span</code>, <code>split</code>, and <code>space</code>. Similarly, the <code>Schedule 4</code> <code>seq spread</code> <code>≫4≫.35&gt;.3</code> has 3 blank values, which represent the default <code>start</code>, <code>span</code>, and <code>space</code>. The <code>Schedule 2</code> and <code>Schedule 3</code> <code>seq spreads</code>, <code>≫2&gt;3&gt;.2&gt;.6</code> and <code>≫3&gt;2&gt;.3&gt;.4</code>, respectively, only have 2 blank values, the <code>start</code> and the <code>span</code>. As an alternative to <code>seq spreads</code> and <code>seq slices</code>, we can use <code>slice</code>-<code>spread</code> hybrids called <code>sleds</code> or <code>spread</code>-<code>slice</code> hybrids called <code>splices</code>. <code>Sleds</code> put the <code>slice</code> elements first (<code>start:stop:step:start&gt;span&gt;split&gt;space</code>), while <code>splices</code> start with the <code>spread</code> elements (<code>start&gt;span&gt;split&gt;space&gt;start:stop:step</code>). The <code>pently</code>schedules are easiest to write as <code>seq spreads</code> and <code>splices</code>, as shown in the table below.</p>
<div id="tbl-3s" class="anchored">
<table class="table">
<caption>Table&nbsp;22: The seq spreads, splices, and sleds that represent the 4 pently schedules</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Schedule</th>
<th>seq spread</th>
<th>splice</th>
<th>sled</th>
<th>seq slice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>≫2&gt;3&gt;.2&gt;.6</td>
<td>≫2&gt;3&gt;.2:.8</td>
<td>:365:1,4:.2&gt;.6</td>
<td>:365:1,4:.2:.8</td>
</tr>
<tr class="even">
<td>3</td>
<td>≫3&gt;2&gt;.3&gt;.4</td>
<td>≫3&gt;2&gt;.3:.7</td>
<td>:365:1,1,3:.3&gt;.4</td>
<td>:365:1,1,3:.3:.7</td>
</tr>
<tr class="odd">
<td>4</td>
<td>≫4≫.35&gt;.3</td>
<td>≫4≫.35:.65</td>
<td>:365:3*1,2:.35&gt;.3</td>
<td>:365:3*1,2:.35:.65</td>
</tr>
<tr class="even">
<td>5</td>
<td>≫≫.38&gt;.24</td>
<td>≫≫.38:.62</td>
<td>:365::.38&gt;.24</td>
<td>:365::.38:.62</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="sec-trans" class="level3">
<h3 class="anchored" data-anchor-id="sec-trans">Yearly transition</h3>
<section id="sec-common" class="level4">
<h4 class="anchored" data-anchor-id="sec-common">Common years</h4>
<p>The <code>pently</code> schedules are important for the transition between years. In common years, the last <code>dek</code> of the year (<code>Dek 36</code>) contains the last <code>pent</code> of the current year (<code>Pent 72</code>), and the first <code>pent</code> of the subsequent year (<code>Pent 0</code>). If these two <code>pents</code> follow the default <code>pently</code> schedule, <code>Schedule 3</code>, the natural rhythm of 3 workdays followed by 2 rest days continues undisrupted. The table below shows the positive and negative <code>doty</code> numbers, names, and types (work or rest) of the days in <code>Dek 36</code> in common years. Notably, while the positive <code>doty</code> numbers continue counting past the end of the year, the negative <code>doty</code> numbers of the current year turn into the negative <code>doty</code> numbers of the subsequent year. The negative <code>doty</code> numbers in <code>Dek 36</code> can thus serve as the bridge from the one year to the next.</p>
<div id="tbl-common" class="anchored">
<table class="table">
<caption>Table&nbsp;23: The days in Dek 36 in common years</caption>
<thead>
<tr class="header">
<th>Pos</th>
<th>Neg</th>
<th>Name</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>360</td>
<td>-5</td>
<td>Nulday</td>
<td>work</td>
</tr>
<tr class="even">
<td>361</td>
<td>-4</td>
<td>Unoday</td>
<td>work</td>
</tr>
<tr class="odd">
<td>362</td>
<td>-3</td>
<td>Duoday</td>
<td>work</td>
</tr>
<tr class="even">
<td>363</td>
<td>-2</td>
<td>Triday</td>
<td>rest</td>
</tr>
<tr class="odd">
<td>364</td>
<td>-1</td>
<td>Quaday</td>
<td>rest</td>
</tr>
<tr class="even">
<td>365</td>
<td>0</td>
<td>Nulday</td>
<td>work</td>
</tr>
<tr class="odd">
<td>366</td>
<td>1</td>
<td>Unoday</td>
<td>work</td>
</tr>
<tr class="even">
<td>367</td>
<td>2</td>
<td>Duoday</td>
<td>work</td>
</tr>
<tr class="odd">
<td>368</td>
<td>3</td>
<td>Triday</td>
<td>rest</td>
</tr>
<tr class="even">
<td>369</td>
<td>4</td>
<td>Quaday</td>
<td>rest</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-leap" class="level4">
<h4 class="anchored" data-anchor-id="sec-leap">Leap years</h4>
<p>In leap years, <code>Dek 36</code> contains the last 6 days of the current year and the first 4 days of the subsequent year. Interestingly, <code>Dek 36</code> always contain 6 workdays and 4 restdays, just like every other <code>dek</code>, but in leaps years these days do not follow the typical order of <code>Schedule 3</code>. Leap years end in 3 restdays instead of 2, because Leap Day (<code>Day 365</code>) is always a holiday. Leap day is always a <code>Penday</code> and always followed by an <code>Nulday</code>. After Leap Day, the normal rhythm of <code>Schedule 3</code> resumes. The table below shows the positive and negative <code>doty</code> numbers of the days in <code>Dek 36</code> in leap years, as well as their names and their types (work or rest).</p>
<div id="tbl-common" class="anchored">
<table class="table">
<caption>Table&nbsp;24: The days in Dek 36 in leap years</caption>
<thead>
<tr class="header">
<th>Pos</th>
<th>Neg</th>
<th>Name</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>360</td>
<td>-6</td>
<td>Nulday</td>
<td>work</td>
</tr>
<tr class="even">
<td>361</td>
<td>-5</td>
<td>Unoday</td>
<td>work</td>
</tr>
<tr class="odd">
<td>362</td>
<td>-4</td>
<td>Duoday</td>
<td>work</td>
</tr>
<tr class="even">
<td>363</td>
<td>-3</td>
<td>Triday</td>
<td>rest</td>
</tr>
<tr class="odd">
<td>364</td>
<td>-2</td>
<td>Quaday</td>
<td>rest</td>
</tr>
<tr class="even">
<td>365</td>
<td>-1</td>
<td>Penday</td>
<td>rest</td>
</tr>
<tr class="odd">
<td>366</td>
<td>0</td>
<td>Nulday</td>
<td>work</td>
</tr>
<tr class="even">
<td>367</td>
<td>1</td>
<td>Unoday</td>
<td>work</td>
</tr>
<tr class="odd">
<td>368</td>
<td>2</td>
<td>Duoday</td>
<td>work</td>
</tr>
<tr class="even">
<td>369</td>
<td>3</td>
<td>Triday</td>
<td>rest</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="sec-holidays" class="level3">
<h3 class="anchored" data-anchor-id="sec-holidays">Holidays</h3>
<p>Leap Day is a important holiday because it occurs only once every four years (except for years that start centuries not divisible by 400) and it results in the only time when there are 3 consecutive restdays in <code>Decalendar</code>. Another <code>Decalendar</code> holiday that only occurs in leap years is Dyad Day. At noon on Dyad Day, the positive and negative <code>.y</code> format <code>stamps</code> are the same (<code>+183.5</code> and <code>-183.5</code>), meaning that 183.5 days have passed in the year and 183.5 days remain in the year. Unlike Leap Day, Dyad Day is naturally a day off. Many Gregorian calendar holidays just so happen to also fall on the first day of a <code>Decalendar</code> <code>pent</code> (<code>Nulday</code> or <code>Quaday</code>). The table below lists 8 such holidays and their <code>doty</code>, <code>dotm</code>, and Gregorian calendar dates.</p>
<div id="tbl-holidays" class="anchored">
<table class="table">
<caption>Table&nbsp;25: Gregorian calendar holidays that happen to fall on <code>Decalendar</code> restdays</caption>
<thead>
<tr class="header">
<th>Name</th>
<th>doty</th>
<th>dotm</th>
<th>date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cinco de Mayo</td>
<td>65</td>
<td>2+04</td>
<td>May 5</td>
</tr>
<tr class="even">
<td>Flag Day</td>
<td>105</td>
<td>3+13</td>
<td>June 14</td>
</tr>
<tr class="odd">
<td>Juneteenth Day</td>
<td>110</td>
<td>3+18</td>
<td>June 19</td>
</tr>
<tr class="even">
<td>Independence Day</td>
<td>125</td>
<td>4+03</td>
<td>July 4</td>
</tr>
<tr class="odd">
<td>All Saints’ Day</td>
<td>245</td>
<td>8+00</td>
<td>November 1</td>
</tr>
<tr class="even">
<td>Veterans’ Day</td>
<td>255</td>
<td>8+10</td>
<td>November 11</td>
</tr>
<tr class="odd">
<td>Boxing Day</td>
<td>300</td>
<td>9+25</td>
<td>December 26</td>
</tr>
<tr class="even">
<td>New Year’s Eve</td>
<td>305</td>
<td>9+31</td>
<td>December 31</td>
</tr>
</tbody>
</table>
</div>
<p>Any holiday with a fixed (rather than floating) date in the Gregorian calendar can easily be added to <code>Decalendar</code>. Holidays with floating dates do not follow easily recognizable patterns. <code>Decalendar</code> recommends redefining such dates to always be on the same <code>doty</code> every year. For example, November 25 (<code>Day 269</code>) is a sensible fixed date for Thanksgiving, because it is exactly 30 days before Christmas (December 25, <code>Day 299</code>) and falls on a <code>Decalendar</code> restday. When assigning fixed dates to floating date holidays, we should choose <code>Decalendar</code> restdays to avoid disrupting the normal rhythm of the <code>pently</code> schedules. Instead of gaining days off from holidays, workers should gain additional time off from their employers. In the United States, the 11 federal holidays (88 hours = 3.6̅ dimes) would translate to 9 <code>Schedule 3</code> days offs (3.6 dimes).</p>
</section>
</section>
<section id="sec-prog" class="level2">
<h2 class="anchored" data-anchor-id="sec-prog">Programming languages</h2>
<section id="sec-js" class="level3">
<h3 class="anchored" data-anchor-id="sec-js">JavaScript</h3>
<p>A key tool in the dissemination of <code>Decalendar</code> will the JavaScript programming language. JavaScript is the language of the web and can run in any browser on any computer.</p>
<p>The three most basic applications are the Calendar Clock Display, the ICS file downloader, and the Pomodoro timer.</p>
<p>Button that switches between <code>dot</code> formats (<code>.y</code>, <code>.m</code>, and <code>.w</code>). The basic elements of <code>Decalendar</code> include the <code>dot</code> formats (<code>.y</code>, <code>.m</code>, and <code>.w</code>) and the series described above should be easy to implement in any high-level programming language, but the implementation examples below will focus on JavaScript and Python. , while Python is a versatile language with strong builtin support for dates and times in its standard library. To implement the</p>
</section>
</section>
<section id="calculations" class="level2">
<h2 class="anchored" data-anchor-id="calculations">Calculations</h2>
<p><code>Declock</code> groups together the 26 <a href="https://en.wikipedia.org/wiki/List_of_UTC_offsets">Coordinated Universal Time (UTC) offsets</a> (-12:00 to +14:00) into 11 time zones (<code>Zone -5</code> to <code>Zone 6</code>) by converting hours into <code>dimes</code> (<span class="math inline">\(hours \div 2.4\)</span>) and rounding to the nearest whole number. This time zone system is simple and facilitates conversion, but locations on the edges of the main time zones may experience a significant difference between <code>Dot 5</code> and <a href="https://en.wikipedia.org/wiki/Noon#Solar_noon">solar noon</a>, the point when the sun reaches its highest position in the sky.</p>
<p>If we decide to prioritize the amount of sunlight at <code>Dot 5</code> over simplicity and ease of conversion, we could convert degrees of longitude into <code>cents</code> or <code>mils</code>, instead of converting hours into <code>dimes</code>. For example, we could say that Mexico City is in <code>Zone -275</code> instead of <code>Zone -3</code>, because the longitude of Mexico City is 99 degrees West, which translates to an offset of -275 <code>mils</code> (<span class="math inline">\(degrees \div .36\)</span>). Essentially, we could create as many additional <code>Declock</code> time zones are desired simply by adding digits to the end of each time zone.</p>
<p>Some programming languages provide direct access to ISO ordinal dates. Subtracting 1 from an ISO ordinal date yields the Dekalendar date:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>datetime(<span class="st">"2023-12-25"</span>).timetuple().tm_yday <span class="op">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.integer</span>(<span class="fu">strftime</span>(<span class="st">"2023-12-25"</span>, <span class="at">format=</span><span class="st">"%j"</span>)) <span class="sc">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode javascript code-with-copy"><code class="sourceCode javascript"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> now <span class="op">=</span> <span class="kw">new</span> <span class="bu">Date</span>(<span class="dv">2023</span><span class="op">,</span> <span class="dv">11</span><span class="op">,</span> <span class="dv">25</span>)<span class="op">,</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> <span class="kw">new</span> <span class="bu">Date</span>(now<span class="op">.</span><span class="fu">getFullYear</span>()<span class="op">,</span> <span class="dv">0</span><span class="op">,</span> <span class="dv">0</span>)<span class="op">,</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>doy <span class="op">=</span> <span class="bu">Math</span><span class="op">.</span><span class="fu">floor</span>((now <span class="op">-</span> start) <span class="op">/</span> <span class="dv">86400000</span>) <span class="op">-</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">console</span><span class="op">.</span><span class="fu">log</span>(doy)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Certain times of day are easier to express as fractions, rather than decimals. This can be done with the <code>Slash</code> operator. For example, 9PM (21:00) is <code>.416̅</code>, which is pronounced <code>Dot four one six vinculum</code>, or <code>5/12</code> which is read <code>five slash twelve</code>.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>